CAEN qtp SDK: cvt_V792.c File Reference
cvt_V792.c File Reference
V792 VME board implementation.
#include <memory.h>
#include <string.h>
#include "cvt_V792.h"
Functions
BOOL cvt_V792_open (cvt_V792_data *p_data, UINT16 base_address, long vme_handle, CVT_QTP_TYPES type)
V792 VME boards data initialization.
BOOL cvt_V792_close (cvt_V792_data *p_data)
V792 VME boards closing and resource free.
BOOL cvt_V792_set_geo_address (cvt_V792_data *p_data, UINT8 value)
Sets the geographical address.
BOOL cvt_V792_get_geo_address (cvt_V792_data *p_data, UINT8 *p_value)
Gets the geographical address.
BOOL cvt_V792_set_MCST_CBLT_address (cvt_V792_data *p_data, UINT8 value)
Sets the MCST\CBLT address.
BOOL cvt_V792_get_MCST_CBLT_address (cvt_V792_data *p_data, UINT8 *p_value)
Gets the MCST\CBLT address.
BOOL cvt_V792_set_bit_set_1 (cvt_V792_data *p_data, UINT16 value)
Set the bit set 1 register.
BOOL cvt_V792_set_bit_clear_1 (cvt_V792_data *p_data, UINT16 value)
Set the bit clear 1 register.
BOOL cvt_V792_set_interrupt_level (cvt_V792_data *p_data, UINT8 value)
Set the interrupt level register.
BOOL cvt_V792_get_interrupt_level (cvt_V792_data *p_data, UINT8 *p_value)
Set the interrupt level register.
BOOL cvt_V792_set_interrupt_vector (cvt_V792_data *p_data, UINT8 value)
Set the interrupt level register.
BOOL cvt_V792_get_interrupt_vector (cvt_V792_data *p_data, UINT8 *p_value)
Get the interrupt vector register.
BOOL cvt_V792_get_status_1 (cvt_V792_data *p_data, UINT16 *p_value)
Get the status 1 register.
BOOL cvt_V792_set_control_1 (cvt_V792_data *p_data, UINT16 value)
Set to control 1 register.
BOOL cvt_V792_get_control_1 (cvt_V792_data *p_data, UINT16 *p_value)
Get the control 1 register.
BOOL cvt_V792_set_bitmask_control_1 (cvt_V792_data *p_data, CVT_V792_CONTROL_1_MSK value)
Set a bitmask to control 1 register.
BOOL cvt_V792_clear_bitmask_control_1 (cvt_V792_data *p_data, CVT_V792_CONTROL_1_MSK value)
Clear a bitmask to control 1 register.
BOOL cvt_V792_set_ader_high (cvt_V792_data *p_data, UINT8 value)
Set the address decoder high register.
BOOL cvt_V792_get_ader_high (cvt_V792_data *p_data, UINT8 *p_value)
Get the address decoder high register.
BOOL cvt_V792_set_ader_low (cvt_V792_data *p_data, UINT8 value)
Set the address decoder low register.
BOOL cvt_V792_get_ader_low (cvt_V792_data *p_data, UINT8 *p_value)
Get the address decoder high register.
BOOL cvt_V792_single_shot_reset (cvt_V792_data *p_data)
Perfoms a single shot reset.
BOOL cvt_V792_set_MCST_CBLT_control (cvt_V792_data *p_data, UINT8 value)
Set the MCST/CBLT Control register.
BOOL cvt_V792_get_MCST_CBLT_control (cvt_V792_data *p_data, UINT8 *p_value)
Get the MCST/CBLT Control register.
BOOL cvt_V792_set_event_trigger (cvt_V792_data *p_data, UINT8 value)
Set the Event trigger register.
BOOL cvt_V792_get_event_trigger (cvt_V792_data *p_data, UINT8 *p_value)
Get the Event trigger register.
BOOL cvt_V792_get_status_2 (cvt_V792_data *p_data, UINT16 *p_value)
Get the status 1 register.
BOOL cvt_V792_set_threshold (cvt_V792_data *p_data, cvt_V792_threshold_id threshold_id, UINT16 value)
Set the specified threshold register.
BOOL cvt_V792_set_dual_range_threshold (cvt_V792_data *p_data, cvt_V792_threshold_id threshold_id, UINT16 value_high, UINT16 value_low)
Set the specified threshold register for dual range board (V965 and V1785).
BOOL cvt_V792_set_bit_set_2 (cvt_V792_data *p_data, UINT16 value)
Set the bit set 2 register.
BOOL cvt_V792_set_bit_clear_2 (cvt_V792_data *p_data, UINT16 value)
Set the bit clear 2 register.
BOOL cvt_V792_set_sliding_scale (cvt_V792_data *p_data, BOOL enable)
Setups the sliding scale feature.
BOOL cvt_V792_set_zero_suppression (cvt_V792_data *p_data, BOOL enable, BOOL step_threshold, const UINT16 *thresholds_buff)
Setups the zero suppression feature.
CVT_DLL_API BOOL cvt_V792_set_dual_range_zero_suppression (cvt_V792_data *p_data, BOOL enable, BOOL step_threshold, const UINT16 *thresholds_buff_high, const UINT16 *thresholds_buff_low)
Setups the zero suppression feature for dual range boards (V965 or V1785).
BOOL cvt_V792_set_overflow_suppression (cvt_V792_data *p_data, BOOL enable)
Setups the overflow suppression feature.
BOOL cvt_V792_set_MEB (cvt_V792_data *p_data, BOOL empty_enable, BOOL auto_incr_enable)
Setups the Multiple Event Buffer.
BOOL cvt_V792_set_event_counter (cvt_V792_data *p_data, BOOL count_all_events, BOOL reset_count)
Setups the event counter.
BOOL cvt_V792_read_MEB (cvt_V792_data *p_data, void *p_buff, UINT32 *p_buff_size)
Reads data from Multiple event buffer and stores to user buffer.
BOOL cvt_V792_set_fast_clear_window (cvt_V792_data *p_data, UINT16 value)
Set the fast clear window register.
BOOL cvt_V792_set_acquisition_mode (cvt_V792_data *p_data, BOOL sliding_scale_enable, BOOL zero_suppression_enable, BOOL overflow_suppression_enable, BOOL empty_enable, BOOL count_all_events)
Setups the acquisition mode parameters.
BOOL cvt_V792_set_interrupt (cvt_V792_data *p_data, UINT8 level, UINT8 vector, UINT8 event_number)
Setups interrupt parameters.
BOOL cvt_V792_set_readout_mode (cvt_V792_data *p_data, BOOL bus_error_enable, BOOL block_end_enable, BOOL align64_enable)
Setups data readout mode parameters.
BOOL cvt_V792_get_status (cvt_V792_data *p_data, BOOL *p_is_data_ready, BOOL *p_is_busy, BOOL *p_is_term_on, BOOL *p_is_buffer_full)
Gets information about board status.
BOOL cvt_V792_set_crate_number (cvt_V792_data *p_data, UINT8 crate_number)
Setups the crate number.
BOOL cvt_V792_set_pedestal (cvt_V792_data *p_data, UINT8 value)
Set the pedestal value.
BOOL cvt_V792_get_event_counter (cvt_V792_data *p_data, UINT32 *p_counter)
Gets the event counter value.
BOOL cvt_V792_get_system_info (cvt_V792_data *p_data, UINT16 *p_firmware_rev, UINT8 *p_piggy_back_type, UINT16 *p_serial_number)
Gets board's system information.
const char * cvt_V792_get_piggy_back_str (cvt_V792_data *p_data, UINT8 piggy_back_type)
Returns ths mounted piggy back type string.
BOOL cvt_V792_software_reset (cvt_V792_data *p_data)
Performs a software reset.
BOOL cvt_V792_data_clear (cvt_V792_data *p_data)
Performs a data clear.
BOOL cvt_V792_read_data (cvt_V792_data *p_data)
Reads new data from MEB and stores into internal queue.
BOOL cvt_V792_peek_event (cvt_V792_data *p_data, UINT32 *out_buff, long *p_out_buff_size, UINT32 *p_event_count, BOOL dequeue)
Tries to peek (i.e. copy but not removing) an event from queue and save data to output buffer.
BOOL cvt_V792_peek_channel_data (cvt_V792_data *p_data, UINT8 channel_index, UINT16 *out_buff, long *p_out_buff_size, UINT32 *p_event_count, BOOL dequeue)
Tries to peek (i.e. copy but not removing) an event from queue and save ADC data for the specific channel to output buffer.
BOOL cvt_V792_inqueue (cvt_V792_data *p_data, const UINT32 *in_buff, UINT32 in_buff_size)
Tries to put in_buff_size data word to queue.
BOOL cvt_V792_dequeue (cvt_V792_data *p_data, UINT32 *out_buff, UINT32 out_buff_size)
Tries to get out_buff_size data word from the queue.
long cvt_V792_get_queue_free (cvt_V792_data *p_data)
Gets the number of free queue space (words).
long cvt_V792_get_queue_length (cvt_V792_data *p_data)
Gets the queue length.
BOOL cvt_V792_set_MCST_CBLT (cvt_V792_data *p_data, UINT8 address, MCST_CBLT_board_pos pos)
Setups MCST/CBLT parameters this board.
const char * cvt_V792_SW_rev (void)
Returns the SDK software release.
Variables
const int CVT_QTP_NUM_CHANNELS []
The number of channels foreach specific board.
Detailed Description
V792 VME board implementation.
Author:
NDA
Version:
1.0
Date:
03/2006
Provides methods, properties and defines to handle V792 VME boards
Definition in file cvt_V792.c.
Function Documentation
CVT_DLL_API BOOL cvt_V792_clear_bitmask_control_1 (cvt_V792_data * p_data, CVT_V792_CONTROL_1_MSK value)
Clear a bitmask to control 1 register.
Clears the bits of the bitmask into the register. The inverted bitmask is ANDed to the actual regiter content
Parameters:
p_data Pointer to board data
value The bitmask to clear: may be a combination of CVT_V792_CONTROL_1_MSK bitmask
Returns:
TRUE: Procedure successfully executed
See also:
CVT_V792_CONTROL_1_MSK
Definition at line 442 of file cvt_V792.c.
References cvt_clear_bitmask(), CVT_V792_CONTROL_1_ADD, CVT_V792_CONTROL_1_AM, CVT_V792_CONTROL_1_DATA_SIZE, FALSE, cvt_V792_data::m_common_data, TRACE, and TRUE.
BOOL cvt_V792_close (cvt_V792_data * p_data)
V792 VME boards closing and resource free.
Provides specific handling for V792 boards closing.
Parameters:
p_data Pointer to board data
Returns:
TRUE: board successfully closed
Note:
Must be called when done with any other board specific API.
Definition at line 197 of file cvt_V792.c.
References cvt_board_close(), FALSE, cvt_V792_data::m_common_data, cvt_V792_data::m_queue, and TRUE.
BOOL cvt_V792_data_clear (cvt_V792_data * p_data)
Performs a data clear.
Pulses the CVT_V792_BSC2_CLEAR_DATA_MSK bit and clears the event counter.
Parameters:
p_data Pointer to board data
Returns:
TRUE: Procedure successfully executed
See also:
CVT_V792_BSC2_CLEAR_DATA_MSK
Definition at line 1533 of file cvt_V792.c.
References CVT_V792_BIT_CLEAR_2_INDEX, CVT_V792_BIT_SET_2_INDEX, CVT_V792_BSC2_CLEAR_DATA_MSK, CVT_V792_EVENT_COUNT_RESET_INDEX, cvt_write_reg(), FALSE, cvt_V792_data::m_common_data, TRACE, and TRUE.
BOOL cvt_V792_dequeue (cvt_V792_data * p_data, UINT32 * out_buff, UINT32 out_buff_size)
Tries to get out_buff_size data word from the queue.
Checks for queue available data words and gets data beginning from m_queue_ini. m_queue_ini will be update: if out_buff!= NULL the data will be stored into it.
Parameters:
p_data Pointer to board data
out_buff Pointer to output buffer (may be NULL)
out_buff_size Size of out_buff (UINT32)
Returns:
TRUE: data removed correctly, FALSE elsewhere (e.g. queue underflow)
Definition at line 1895 of file cvt_V792.c.
References cvt_V792_get_queue_length(), CVT_V792_QUEUE_SIZE_DWORD, FALSE, cvt_V792_data::m_queue, cvt_V792_data::m_queue_ini, and TRUE.
Referenced by cvt_V792_peek_channel_data(), and cvt_V792_peek_event().
BOOL cvt_V792_get_ader_high (cvt_V792_data * p_data, UINT8 * p_value)
Get the address decoder high register.
Reads the address decoder high register.
Parameters:
p_data Pointer to board data
p_value The value read
Returns:
TRUE: Procedure successfully executed
Definition at line 472 of file cvt_V792.c.
References cvt_read_reg(), CVT_V792_ADER_HIGH_INDEX, FALSE, cvt_V792_data::m_common_data, TRACE, and TRUE.
BOOL cvt_V792_get_ader_low (cvt_V792_data * p_data, UINT8 * p_value)
Get the address decoder high register.
Reads the address decoder low register.
Parameters:
p_data Pointer to board data
p_value The value read
Returns:
TRUE: Procedure successfully executed
Definition at line 503 of file cvt_V792.c.
References cvt_read_reg(), CVT_V792_ADER_LOW_INDEX, FALSE, cvt_V792_data::m_common_data, TRACE, and TRUE.
BOOL cvt_V792_get_control_1 (cvt_V792_data * p_data, UINT16 * p_value)
Get the control 1 register.
Reads the control 1 register.
Parameters:
p_data Pointer to board data
p_value The value read
Returns:
TRUE: Procedure successfully executed
Definition at line 411 of file cvt_V792.c.
References cvt_read_reg(), CVT_V792_CONTROL_1_INDEX, FALSE, cvt_V792_data::m_common_data, TRACE, and TRUE.
BOOL cvt_V792_get_event_counter (cvt_V792_data * p_data, UINT32 * p_counter)
Gets the event counter value.
Gets the event counter actual value.
Parameters:
p_data Pointer to board data
p_counter Pointer to the counter value.
Returns:
TRUE: Procedure successfully executed
Definition at line 1417 of file cvt_V792.c.
References cvt_read_reg(), CVT_V792_EVENT_COUNTER_HIGH_INDEX, CVT_V792_EVENT_COUNTER_LOW_INDEX, FALSE, cvt_V792_data::m_common_data, TRACE, and TRUE.
BOOL cvt_V792_get_event_trigger (cvt_V792_data * p_data, UINT8 * p_value)
Get the Event trigger register.
Reads the event trigger register.
Parameters:
p_data Pointer to board data
p_value The value read
Returns:
TRUE: Procedure successfully executed
Definition at line 580 of file cvt_V792.c.
References cvt_read_reg(), CVT_V792_EVENT_TRG_INDEX, FALSE, cvt_V792_data::m_common_data, TRACE, and TRUE.
BOOL cvt_V792_get_geo_address (cvt_V792_data * p_data, UINT8 * p_value)
Gets the geographical address.
Reads the geographical address register.
Parameters:
p_data Pointer to board data
p_value The value read
Returns:
TRUE: Procedure successfully executed
Definition at line 241 of file cvt_V792.c.
References cvt_read_reg(), CVT_V792_GEO_ADDRESS_INDEX, FALSE, cvt_V792_data::m_common_data, TRACE, and TRUE.
BOOL cvt_V792_get_interrupt_level (cvt_V792_data * p_data, UINT8 * p_value)
Set the interrupt level register.
Reads the interrupt level register.
Parameters:
p_data Pointer to board data
p_value The value read
Returns:
TRUE: Procedure successfully executed
Definition at line 333 of file cvt_V792.c.
References cvt_read_reg(), CVT_V792_INT_LEVEL_INDEX, FALSE, cvt_V792_data::m_common_data, TRACE, and TRUE.
BOOL cvt_V792_get_interrupt_vector (cvt_V792_data * p_data, UINT8 * p_value)
Get the interrupt vector register.
Reads the interrupt vector register.
Parameters:
p_data Pointer to board data
p_value The value read
Returns:
TRUE: Procedure successfully executed
Definition at line 364 of file cvt_V792.c.
References cvt_read_reg(), CVT_V792_INT_VECTOR_INDEX, FALSE, cvt_V792_data::m_common_data, TRACE, and TRUE.
BOOL cvt_V792_get_MCST_CBLT_address (cvt_V792_data * p_data, UINT8 * p_value)
Gets the MCST\CBLT address.
Reads the MCST\CBLT address register. This register contains the most significant bits of the MCST/CBLT address of the module set via VME.
Parameters:
p_data Pointer to board data
p_value The value read
Returns:
TRUE: Procedure successfully executed
Definition at line 272 of file cvt_V792.c.
References cvt_read_reg(), CVT_V792_MCST_CBLT_ADDRESS_INDEX, FALSE, cvt_V792_data::m_common_data, TRACE, and TRUE.
BOOL cvt_V792_get_MCST_CBLT_control (cvt_V792_data * p_data, UINT8 * p_value)
Get the MCST/CBLT Control register.
Reads the MCST/CBLT Control register.
Parameters:
p_data Pointer to board data
p_value The value read
Returns:
TRUE: Procedure successfully executed
Definition at line 549 of file cvt_V792.c.
References cvt_read_reg(), CVT_V792_MCST_CBLT_CTRL_INDEX, FALSE, cvt_V792_data::m_common_data, TRACE, and TRUE.
const char * cvt_V792_get_piggy_back_str (cvt_V792_data * p_data, UINT8 piggy_back_type)
Returns ths mounted piggy back type string.
Parameters:
p_data Pointer to board data
piggy_back_type The piggy back type numerical value (as returned from BOOL cvt_V792_get_system_info(cvt_V792_data* p_data, UINT16 *p_firmware_rev, UINT8 *p_piggy_back_type, UINT16 *p_serial_number).
Returns:
A user friendly string describing the piggy back type
Definition at line 1483 of file cvt_V792.c.
long cvt_V792_get_queue_free (cvt_V792_data * p_data)
Gets the number of free queue space (words).
Parameters:
p_data Pointer to board data
Returns:
The number of free queue space (UINT32 words)
Definition at line 1929 of file cvt_V792.c.
References CVT_V792_QUEUE_SIZE_DWORD, cvt_V792_data::m_queue_end, and cvt_V792_data::m_queue_ini.
Referenced by cvt_V792_inqueue(), and cvt_V792_read_data().
long cvt_V792_get_queue_length (cvt_V792_data * p_data)
Gets the queue length.
Parameters:
p_data Pointer to board data
Returns:
The queue length (UINT32 words)
Definition at line 1937 of file cvt_V792.c.
References CVT_V792_QUEUE_SIZE_DWORD, cvt_V792_data::m_queue_end, and cvt_V792_data::m_queue_ini.
Referenced by cvt_V792_dequeue().
BOOL cvt_V792_get_status (cvt_V792_data * p_data, BOOL * p_is_data_ready, BOOL * p_is_busy, BOOL * p_is_term_on, BOOL * p_is_buffer_full)
Gets information about board status.
Parameters:
p_data Pointer to board data
p_is_data_ready Returns TRUE if data is ready.
p_is_busy Returns TRUE if board is busy.
p_is_term_on Returns TRUE if term bit is on.
p_is_buffer_full Returns TRUE if buffer is full.
Returns:
TRUE: Procedure successfully executed
Definition at line 1354 of file cvt_V792.c.
References cvt_read_reg(), CVT_V792_STATUS_1_INDEX, CVT_V792_STATUS_2_INDEX, CVT_V792_STS1_BUSY_MSK, CVT_V792_STS1_DREADY_MSK, CVT_V792_STS1_TERM_ON_MSK, CVT_V792_STS2_BUFFER_FULL_MSK, FALSE, cvt_V792_data::m_common_data, TRACE, and TRUE.
BOOL cvt_V792_get_status_1 (cvt_V792_data * p_data, UINT16 * p_value)
Get the status 1 register.
Reads the status 1 register.
Parameters:
p_data Pointer to board data
p_value The value read
Returns:
TRUE: Procedure successfully executed
Definition at line 380 of file cvt_V792.c.
References cvt_read_reg(), CVT_V792_STATUS_1_INDEX, FALSE, cvt_V792_data::m_common_data, TRACE, and TRUE.
BOOL cvt_V792_get_status_2 (cvt_V792_data * p_data, UINT16 * p_value)
Get the status 1 register.
Reads the status 2 register.
Parameters:
p_data Pointer to board data
p_value The value read
Returns:
TRUE: Procedure successfully executed
Definition at line 596 of file cvt_V792.c.
References cvt_read_reg(), CVT_V792_STATUS_2_INDEX, FALSE, cvt_V792_data::m_common_data, TRACE, and TRUE.
BOOL cvt_V792_get_system_info (cvt_V792_data * p_data, UINT16 * p_firmware_rev, UINT8 * p_piggy_back_type, UINT16 * p_serial_number)
Gets board's system information.
Reads the firmware revision register, the board type and the serial number.
Parameters:
p_data Pointer to board data
p_firmware_rev The firmare release (MSB major release, LSB minor release).
p_piggy_back_type The mounted piggy back type.
p_serial_number The serial number.
Returns:
TRUE: Procedure successfully executed
Definition at line 1442 of file cvt_V792.c.
References cvt_read_reg(), CVT_V792_FW_REV_INDEX, CVT_V792_GET_PIGGY_BACK_TYPE, CVT_V792_ROM_SERIAL_0_INDEX, CVT_V792_ROM_SERIAL_1_INDEX, CVT_V792_STATUS_2_INDEX, FALSE, cvt_V792_data::m_common_data, TRACE, and TRUE.
BOOL cvt_V792_inqueue (cvt_V792_data * p_data, const UINT32 * in_buff, UINT32 in_buff_size)
Tries to put in_buff_size data word to queue.
Checks for the queue available free words and stores data beginning from m_queue_end. m_queue_end will be update
Parameters:
p_data Pointer to board data
in_buff Pointer to input buffer
in_buff_size Size of in_buff (UINT32)
Returns:
TRUE: data stored correctly FALSE elsewhere (e.g. queue overflow)
Definition at line 1867 of file cvt_V792.c.
References cvt_V792_get_queue_free(), CVT_V792_QUEUE_SIZE_DWORD, FALSE, cvt_V792_data::m_queue, cvt_V792_data::m_queue_end, and TRUE.
Referenced by cvt_V792_read_data().
BOOL cvt_V792_open (cvt_V792_data * p_data, UINT16 base_address, long vme_handle, CVT_QTP_TYPES type)
V792 VME boards data initialization.
Provides specific handling for V792 boards opening.
Parameters:
p_data Pointer to board data
base_address The board base address (MSW)
vme_handle The VME handle
type The board type : it must be a CVT_QTP_TYPES value
Returns:
TRUE: board successfully opened
Note:
Must be called before any other board specific API.
See also:
CVT_QTP_TYPES
< The board is V792A
< The board is V792N
< The board is V862A
< The board is V965
< The board is V965A
< The board is V785A
< The board is V785N
< The board is V1785
< The board is V775A
< The board is V775N
Definition at line 150 of file cvt_V792.c.
References cvt_board_open(), CVT_V1785, CVT_V775_TYPE_A, CVT_V775_TYPE_N, CVT_V785_TYPE_A, CVT_V785_TYPE_N, CVT_V792_QUEUE_SIZE_DWORD, cvt_V792_set_MCST_CBLT(), CVT_V792_TYPE_A, CVT_V792_TYPE_N, CVT_V862_TYPE_A, CVT_V965, CVT_V965_TYPE_A, FALSE, cvt_V792_data::m_common_data, cvt_V792_data::m_queue, cvt_V792_data::m_type, cvt_board_data::set_MCST_CBLT, TRACE, TRACE1, and TRUE.
cvt_V792_peek_channel_data (cvt_V792_data * p_data, UINT8 channel_index, UINT16 * out_buff, long * p_out_buff_size, UINT32 * p_event_count, BOOL dequeue)
Tries to peek (i.e. copy but not removing) an event from queue and save ADC data for the specific channel to output buffer.
Scans the queue beginning from m_queue_ini, searching for an event block, and stores data output stream.
Parameters:
p_data Pointer to board data
channel_index The channel to get data from
out_buff Pointer to output buffer
p_out_buff_size Size of out_buff (UINT32). The number of data written into out_buff (UINT32) on exit.
p_event_count Requested event count. The found event count, on exit
dequeue If TRUE removes the found events from queue. !!! WARNING !!! the whole event will be deleted (i.e. other channels' data will be lost too)
Returns:
TRUE: some event found, FALSE elsewhere
Definition at line 1695 of file cvt_V792.c.
References CVT_QTP_DATA_TYPE_MSK, CVT_QTP_DATUM, CVT_QTP_GET_EOB_EVENT_COUNT, CVT_QTP_IS_EOB, CVT_QTP_IS_HEADER, CVT_V1785, CVT_V1785_GET_DATUM_ADC, CVT_V1785_GET_DATUM_CH, CVT_V1785_GET_DATUM_GEO, CVT_V1785_GET_DATUM_OV, CVT_V1785_GET_DATUM_UN, CVT_V775_GET_DATUM_ADC, CVT_V775_GET_DATUM_GEO, CVT_V775_GET_DATUM_OV, CVT_V775_GET_DATUM_UN, CVT_V775_TYPE_A, CVT_V775_TYPE_N, CVT_V775A_GET_DATUM_CH, CVT_V775N_GET_DATUM_CH, CVT_V785_GET_DATUM_ADC, CVT_V785_GET_DATUM_GEO, CVT_V785_GET_DATUM_OV, CVT_V785_GET_DATUM_UN, CVT_V785_TYPE_A, CVT_V785_TYPE_N, CVT_V785A_GET_DATUM_CH, CVT_V785N_GET_DATUM_CH, cvt_V792_dequeue(), CVT_V792_GET_DATUM_ADC, CVT_V792_GET_DATUM_GEO, CVT_V792_GET_DATUM_OV, CVT_V792_GET_DATUM_UN, CVT_V792_QUEUE_SIZE_DWORD, CVT_V792_TYPE_A, CVT_V792_TYPE_N, CVT_V792A_GET_DATUM_CH, CVT_V792N_GET_DATUM_CH, CVT_V965, CVT_V965_GET_DATUM_ADC, CVT_V965_GET_DATUM_CH, CVT_V965_GET_DATUM_GEO, CVT_V965_GET_DATUM_OV, CVT_V965_GET_DATUM_UN, CVT_V965_TYPE_A, CVT_V965A_GET_DATUM_CH, FALSE, cvt_V792_data::m_queue, cvt_V792_data::m_queue_end, cvt_V792_data::m_queue_ini, cvt_V792_data::m_type, TRACE1, and TRUE.
BOOL cvt_V792_peek_event (cvt_V792_data * p_data, UINT32 * out_buff, long * p_out_buff_size, UINT32 * p_event_count, BOOL dequeue)
Tries to peek (i.e. copy but not removing) an event from queue and save data to output buffer.
Scans the queue beginning from m_queue_ini, searching for an event block, and stores data output stream.
Parameters:
p_data Pointer to board data
out_buff Pointer to output buffer
p_out_buff_size Size of out_buff (UINT32). The number of data written into out_buff (UINT32) on exit.
p_event_count The found event count
dequeue If TRUE removes the found events from queue
Returns:
TRUE: some event found FALSE elsewhere
Definition at line 1609 of file cvt_V792.c.
References CVT_QTP_GET_EOB_EVENT_COUNT, CVT_QTP_IS_EOB, CVT_QTP_IS_HEADER, cvt_V792_dequeue(), CVT_V792_QUEUE_SIZE_DWORD, FALSE, cvt_V792_data::m_queue, cvt_V792_data::m_queue_end, cvt_V792_data::m_queue_ini, and TRUE.
BOOL cvt_V792_read_data (cvt_V792_data * p_data)
Reads new data from MEB and stores into internal queue.
Reads the largest allowed buffer (queue free size) from MEB and stores into queue
Parameters:
p_data Pointer to board data
Returns:
TRUE: Procedure successfully executed
Definition at line 1565 of file cvt_V792.c.
References cvt_V792_get_queue_free(), cvt_V792_inqueue(), cvt_V792_read_MEB(), FALSE, TRACE, and TRUE.
BOOL cvt_V792_read_MEB (cvt_V792_data * p_data, void * p_buff, UINT32 * p_buff_size)
Reads data from Multiple event buffer and stores to user buffer.
Call cvt_FIFO_BLT_read for Multiple Event Buffer and stores data into user buffer. If the returned data is just a V792 not valid datum, this is discarded.
Parameters:
p_data Pointer to board data
p_buff The target buffer: caller allocated
p_buff_size The buffer size (bytes). On exit will holds the number of bytes really read.
Returns:
TRUE: Procedure successfully executed
See also:
cvt_FIFO_BLT_read
Definition at line 1181 of file cvt_V792.c.
References cvt_FIFO_BLT_read(), CVT_QTP_IS_NOT_VALID_DATUM, CVT_V792_OUT_BUFFER_ADD, CVT_V792_OUT_BUFFER_AM, CVT_V792_OUT_BUFFER_DATA_SIZE, FALSE, cvt_V792_data::m_common_data, and TRUE.
Referenced by cvt_V792_read_data().
BOOL cvt_V792_set_acquisition_mode (cvt_V792_data * p_data, BOOL sliding_scale_enable, BOOL zero_suppression_enable, BOOL overflow_suppression_enable, BOOL empty_enable, BOOL count_all_events)
Setups the acquisition mode parameters.
Setups the relevant parameters for the acquisition mode.
Parameters:
p_data Pointer to board data
sliding_scale_enable Enable/Disable the sliding scale feature.
zero_suppression_enable Enable/Disable the zero suppression feature.
overflow_suppression_enable Enable/Disable the overflow suppression feature.
empty_enable Enable/Disable empty event storing feature.
count_all_events Enable counting all triggers or accepted one only.
Returns:
TRUE: Procedure successfully executed
Definition at line 1215 of file cvt_V792.c.
References CVT_V792_BIT_CLEAR_2_INDEX, CVT_V792_BIT_SET_2_INDEX, CVT_V792_BSC2_ALL_TRG_MSK, CVT_V792_BSC2_EMPTY_EN_MSK, CVT_V792_BSC2_LOW_THR_DIS_MSK, CVT_V792_BSC2_OVER_RANGE_DIS_MSK, CVT_V792_BSC2_SLIDE_EN_MSK, cvt_write_reg(), FALSE, cvt_V792_data::m_common_data, TRACE, and TRUE.
CVT_DLL_API BOOL cvt_V792_set_ader_high (cvt_V792_data * p_data, UINT8 value)
Set the address decoder high register.
Writes the specified value to the address decoder high register.
Parameters:
p_data Pointer to board data
value The value to set
Returns:
TRUE: Procedure successfully executed
Definition at line 457 of file cvt_V792.c.
References CVT_V792_ADER_HIGH_INDEX, cvt_write_reg(), FALSE, cvt_V792_data::m_common_data, TRACE, and TRUE.
BOOL cvt_V792_set_ader_low (cvt_V792_data * p_data, UINT8 value)
Set the address decoder low register.
Writes the specified value to the address decoder low register.
Parameters:
p_data Pointer to board data
value The value to set
Returns:
TRUE: Procedure successfully executed
Definition at line 488 of file cvt_V792.c.
References CVT_V792_ADER_LOW_INDEX, cvt_write_reg(), FALSE, cvt_V792_data::m_common_data, TRACE, and TRUE.
BOOL cvt_V792_set_bit_clear_1 (cvt_V792_data * p_data, UINT16 value)
Set the bit clear 1 register.
Writes the specified value to the bit clear 1 register.
Parameters:
p_data Pointer to board data
value The value to set
Returns:
TRUE: Procedure successfully executed
Definition at line 303 of file cvt_V792.c.
References CVT_V792_BIT_CLEAR_1_INDEX, cvt_write_reg(), FALSE, cvt_V792_data::m_common_data, TRACE, and TRUE.
BOOL cvt_V792_set_bit_clear_2 (cvt_V792_data * p_data, UINT16 value)
Set the bit clear 2 register.
Writes the specified value to the bit clear 2 register.
Parameters:
p_data Pointer to board data
value The value to set
Returns:
TRUE: Procedure successfully executed
Definition at line 831 of file cvt_V792.c.
References CVT_V792_BIT_CLEAR_2_INDEX, cvt_write_reg(), FALSE, cvt_V792_data::m_common_data, TRACE, and TRUE.
BOOL cvt_V792_set_bit_set_1 (cvt_V792_data * p_data, UINT16 value)
Set the bit set 1 register.
Writes the specified value to the bit set 1 register.
Parameters:
p_data Pointer to board data
value The value to set
Returns:
TRUE: Procedure successfully executed
Definition at line 288 of file cvt_V792.c.
References CVT_V792_BIT_SET_1_INDEX, cvt_write_reg(), FALSE, cvt_V792_data::m_common_data, TRACE, and TRUE.
BOOL cvt_V792_set_bit_set_2 (cvt_V792_data * p_data, UINT16 value)
Set the bit set 2 register.
Writes the specified value to the bit set 2 register.
Parameters:
p_data Pointer to board data
value The value to set
Returns:
TRUE: Procedure successfully executed
Definition at line 816 of file cvt_V792.c.
References CVT_V792_BIT_SET_2_INDEX, cvt_write_reg(), FALSE, cvt_V792_data::m_common_data, TRACE, and TRUE.
BOOL cvt_V792_set_bitmask_control_1 (cvt_V792_data * p_data, CVT_V792_CONTROL_1_MSK value)
Set a bitmask to control 1 register.
Sets the bits of the bitmask into the register. The bitmask is ORed to the actual regiter content
Parameters:
p_data Pointer to board data
value The bitmask to set : may be a combination of CVT_V792_CONTROL_1_MSK bitmask
Returns:
TRUE: Procedure successfully executed
See also:
CVT_V792_CONTROL_1_MSK
Definition at line 427 of file cvt_V792.c.
References cvt_set_bitmask(), CVT_V792_CONTROL_1_ADD, CVT_V792_CONTROL_1_AM, CVT_V792_CONTROL_1_DATA_SIZE, FALSE, cvt_V792_data::m_common_data, TRACE, and TRUE.
BOOL cvt_V792_set_control_1 (cvt_V792_data * p_data, UINT16 value)
Set to control 1 register.
Writes the specified value to the control 1 register.
Parameters:
p_data Pointer to board data
value The value to write
Returns:
TRUE: Procedure successfully executed
See also:
CVT_V792_CONTROL_1_MSK
Definition at line 396 of file cvt_V792.c.
References CVT_V792_CONTROL_1_INDEX, cvt_write_reg(), FALSE, cvt_V792_data::m_common_data, TRACE, and TRUE.
BOOL cvt_V792_set_crate_number (cvt_V792_data * p_data, UINT8 crate_number)
Setups the crate number.
Parameters:
p_data Pointer to board data
crate_number The crate number.
Returns:
TRUE: Procedure successfully executed
Definition at line 1383 of file cvt_V792.c.
References CVT_V792_CRATE_SELECT_INDEX, cvt_write_reg(), FALSE, cvt_V792_data::m_common_data, TRACE, and TRUE.
BOOL cvt_V792_set_dual_range_threshold (cvt_V792_data * p_data, cvt_V792_threshold_id threshold_id, UINT16 value_high, UINT16 value_low)
Set the specified threshold register for dual range board (V965 and V1785).
Writes the specified value to the specified threshold register as high and low part. If threshold_id is CVT_V792_THRESHOLD_ALL every threshold will be setted to the same value.
Parameters:
p_data Pointer to board data
threshold_id The threshold to set. It must be a cvt_V792_threshold_id valid id.
value_high The high value to set : Threshold value and Kill bit (CVT_V792_THRESHOLD_KILL_MSK) If the kill bit be isn't setted the channel will be disabled
value_low The low value to set : Threshold value and Kill bit (CVT_V792_THRESHOLD_KILL_MSK) If the kill bit be isn't setted the channel will be disabled
Returns:
TRUE: Procedure successfully executed
See also:
cvt_V792_threshold_id
CVT_V792_THRESHOLD_KILL_MSK
< The board is V965
< The board is V965A
< The board is V1785
Definition at line 716 of file cvt_V792.c.
References CVT_QTP_NUM_CHANNELS, CVT_V1785, CVT_V792_THRESHOLD_0, CVT_V792_THRESHOLD_0_INDEX, CVT_V792_THRESHOLD_1, CVT_V792_THRESHOLD_10, CVT_V792_THRESHOLD_11, CVT_V792_THRESHOLD_12, CVT_V792_THRESHOLD_13, CVT_V792_THRESHOLD_14, CVT_V792_THRESHOLD_15, CVT_V792_THRESHOLD_16, CVT_V792_THRESHOLD_17, CVT_V792_THRESHOLD_18, CVT_V792_THRESHOLD_19, CVT_V792_THRESHOLD_2, CVT_V792_THRESHOLD_20, CVT_V792_THRESHOLD_21, CVT_V792_THRESHOLD_22, CVT_V792_THRESHOLD_23, CVT_V792_THRESHOLD_24, CVT_V792_THRESHOLD_25, CVT_V792_THRESHOLD_26, CVT_V792_THRESHOLD_27, CVT_V792_THRESHOLD_28, CVT_V792_THRESHOLD_29, CVT_V792_THRESHOLD_3, CVT_V792_THRESHOLD_30, CVT_V792_THRESHOLD_31, CVT_V792_THRESHOLD_4, CVT_V792_THRESHOLD_5, CVT_V792_THRESHOLD_6, CVT_V792_THRESHOLD_7, CVT_V792_THRESHOLD_8, CVT_V792_THRESHOLD_9, CVT_V792_THRESHOLD_ALL, CVT_V965, CVT_V965_TYPE_A, cvt_write_reg(), FALSE, cvt_V792_data::m_common_data, cvt_V792_data::m_type, TRACE1, and TRUE.
BOOL cvt_V792_set_dual_range_zero_suppression (cvt_V792_data * p_data, BOOL enable, BOOL step_threshold, const UINT16 * thresholds_buff_high, const UINT16 * thresholds_buff_low)
Setups the zero suppression feature for dual range boards (V965 or V1785).
Enable/ Disable zero suppression and setups other relevant parameters.
Parameters:
p_data Pointer to board data
enable Enable/disable the zero suppression (low threshold check).
step_threshold If setted the comparison is ADC CONVERTED VALUE < THRESHOLD VALUE x 2, otherwise ADC CONVERTED VALUE < THRESHOLD VALUE x 16
thresholds_buff_high The high thresholds buffer: It must contain as many values as specified for the board type (CVT_QTP_NUM_CHANNELS). It may be NULL (e.g. when disabling this feature or the thresholds are already setted) The value consists of the threshold level and the kill bit (CVT_V792_THRESHOLD_KILL_MSK) If the kill bit be isn't setted the channel will be disabled
thresholds_buff_low The low thresholds buffer: It must contain as many values as specified for the board type (CVT_QTP_NUM_CHANNELS). It may be NULL (e.g. when disabling this feature or the thresholds are already setted) The value consists of the threshold level and the kill bit (CVT_V792_THRESHOLD_KILL_MSK) If the kill bit be isn't setted the channel will be disabled
Returns:
TRUE: Procedure successfully executed
See also:
CVT_V792_THRESHOLD_KILL_MSK
< The board is V965
< The board is V965A
< The board is V1785
Definition at line 963 of file cvt_V792.c.
References CVT_QTP_NUM_CHANNELS, CVT_V1785, CVT_V792_BIT_CLEAR_2_INDEX, CVT_V792_BIT_SET_2_INDEX, CVT_V792_BSC2_LOW_THR_DIS_MSK, CVT_V792_BSC2_STEP_TH_MSK, CVT_V792_THRESHOLD_0, CVT_V792_THRESHOLD_0_INDEX, CVT_V965, CVT_V965_TYPE_A, cvt_write_reg(), FALSE, cvt_V792_data::m_common_data, cvt_V792_data::m_type, TRACE, TRACE1, and TRUE.
BOOL cvt_V792_set_event_counter (cvt_V792_data * p_data, BOOL count_all_events, BOOL reset_count)
Setups the event counter.
Setups the relevant parameters for the event counter.
Parameters:
p_data Pointer to board data
count_all_events Enable counting all events or accepted ones only.
reset_count If TRUE resets the event counter.
Returns:
TRUE: Procedure successfully executed
Definition at line 1139 of file cvt_V792.c.
References CVT_V792_BIT_CLEAR_2_INDEX, CVT_V792_BIT_SET_2_INDEX, CVT_V792_BSC2_ALL_TRG_MSK, CVT_V792_EVENT_COUNT_RESET_INDEX, cvt_write_reg(), FALSE, cvt_V792_data::m_common_data, TRACE, and TRUE.
BOOL cvt_V792_set_event_trigger (cvt_V792_data * p_data, UINT8 value)
Set the Event trigger register.
Writes the specified value to the Event trigger register.
Parameters:
p_data Pointer to board data
value The value to set
Returns:
TRUE: Procedure successfully executed
Definition at line 565 of file cvt_V792.c.
References CVT_V792_EVENT_TRG_INDEX, cvt_write_reg(), FALSE, cvt_V792_data::m_common_data, TRACE, and TRUE.
BOOL cvt_V792_set_fast_clear_window (cvt_V792_data * p_data, UINT16 value)
Set the fast clear window register.
Writes the specified value to the fast clear window register.
Parameters:
p_data Pointer to board data
value The value to set
Returns:
TRUE: Procedure successfully executed
Definition at line 1200 of file cvt_V792.c.
References CVT_V792_FCLR_WND_INDEX, cvt_write_reg(), FALSE, cvt_V792_data::m_common_data, TRACE, and TRUE.
BOOL cvt_V792_set_geo_address (cvt_V792_data * p_data, UINT8 value)
Sets the geographical address.
Writes the geographical address register.
Parameters:
p_data Pointer to board data
value The value to write
Returns:
TRUE: Procedure successfully executed
Definition at line 226 of file cvt_V792.c.
References CVT_V792_GEO_ADDRESS_INDEX, cvt_write_reg(), FALSE, cvt_V792_data::m_common_data, TRACE, and TRUE.
BOOL cvt_V792_set_interrupt (cvt_V792_data * p_data, UINT8 level, UINT8 vector, UINT8 event_number)
Setups interrupt parameters.
Setups the relevant parameters for interrupt usage.
Parameters:
p_data Pointer to board data
level The interrupt level.
vector The interrupt vector.
event_number The number of events to get an interrupt (setting 0 interrupt feature is disabled).
Returns:
TRUE: Procedure successfully executed
Definition at line 1267 of file cvt_V792.c.
References CVT_V792_EVENT_TRG_INDEX, CVT_V792_INT_LEVEL_INDEX, CVT_V792_INT_VECTOR_INDEX, cvt_write_reg(), FALSE, cvt_V792_data::m_common_data, TRACE, and TRUE.
BOOL cvt_V792_set_interrupt_level (cvt_V792_data * p_data, UINT8 value)
Set the interrupt level register.
Writes the specified value to the interrupt level register.
Parameters:
p_data Pointer to board data
value The value to set
Returns:
TRUE: Procedure successfully executed
Definition at line 318 of file cvt_V792.c.
References CVT_V792_INT_LEVEL_INDEX, cvt_write_reg(), FALSE, cvt_V792_data::m_common_data, TRACE, and TRUE.
BOOL cvt_V792_set_interrupt_vector (cvt_V792_data * p_data, UINT8 value)
Set the interrupt level register.
Writes the specified value to the interrupt vector register.
Parameters:
p_data Pointer to board data
value The value to set
Returns:
TRUE: Procedure successfully executed
Definition at line 349 of file cvt_V792.c.
References CVT_V792_INT_VECTOR_INDEX, cvt_write_reg(), FALSE, cvt_V792_data::m_common_data, TRACE, and TRUE.
BOOL cvt_V792_set_MCST_CBLT (cvt_V792_data * p_data, UINT8 address, MCST_CBLT_board_pos pos)
Setups MCST/CBLT parameters this board.
Setups the relevant parameters for MCST/CBLT usage.
Parameters:
p_data Pointer to board data.
address The MCST/CBLT address.
pos The board position into the MCST / CBLT chain: it must be a MCST_CBLT_board_pos identifier
Returns:
TRUE: Procedure successfully executed
See also:
MCST_CBLT_board_pos
Definition at line 1947 of file cvt_V792.c.
References CVT_V792_MCCTRL_DISABLED_BOARD_MSK, CVT_V792_MCCTRL_FIRST_BOARD_MSK, CVT_V792_MCCTRL_LAST_BOARD_MSK, CVT_V792_MCCTRL_MID_BOARD_MSK, CVT_V792_MCST_CBLT_ADDRESS_INDEX, CVT_V792_MCST_CBLT_CTRL_INDEX, cvt_write_reg(), FALSE, cvt_V792_data::m_common_data, MCST_CBLT_board_disabled, MCST_CBLT_board_pos_first, MCST_CBLT_board_pos_last, MCST_CBLT_board_pos_mid, TRACE, TRACE1, and TRUE.
Referenced by cvt_V792_open().
BOOL cvt_V792_set_MCST_CBLT_address (cvt_V792_data * p_data, UINT8 value)
Sets the MCST\CBLT address.
Writes the geographical address register. This register contains the most significant bits of the MCST/CBLT address of the module set via VME.
Parameters:
p_data Pointer to board data
value The value to write
Returns:
TRUE: Procedure successfully executed
Definition at line 257 of file cvt_V792.c.
References CVT_V792_MCST_CBLT_ADDRESS_INDEX, cvt_write_reg(), FALSE, cvt_V792_data::m_common_data, TRACE, and TRUE.
BOOL cvt_V792_set_MCST_CBLT_control (cvt_V792_data * p_data, UINT8 value)
Set the MCST/CBLT Control register.
Writes the specified value to the MCST/CBLT Control register.
Parameters:
p_data Pointer to board data
value The value to set
Returns:
TRUE: Procedure successfully executed
Definition at line 534 of file cvt_V792.c.
References CVT_V792_MCST_CBLT_CTRL_INDEX, cvt_write_reg(), FALSE, cvt_V792_data::m_common_data, TRACE, and TRUE.
BOOL cvt_V792_set_MEB (cvt_V792_data * p_data, BOOL empty_enable, BOOL auto_incr_enable)
Setups the Multiple Event Buffer.
Setups the relevant parameters for the Multiple Event Buffer.
Parameters:
p_data Pointer to board data
empty_enable Enable/disable storing events with no data (only header and EOB).
auto_incr_enable Enable/disable the event counter autoincrement feature.
Returns:
TRUE: Procedure successfully executed
Definition at line 1089 of file cvt_V792.c.
References CVT_V792_BIT_CLEAR_2_INDEX, CVT_V792_BIT_SET_2_INDEX, CVT_V792_BSC2_AUTO_INC_MSK, CVT_V792_BSC2_EMPTY_EN_MSK, cvt_write_reg(), FALSE, cvt_V792_data::m_common_data, TRACE, and TRUE.
BOOL cvt_V792_set_overflow_suppression (cvt_V792_data * p_data, BOOL enable)
Setups the overflow suppression feature.
Enable/ Disable overflow suppression and setups other relevant parameters.
Parameters:
p_data Pointer to board data
enable Enable/disable the overflow suppression.
Returns:
TRUE: Procedure successfully executed
Definition at line 1059 of file cvt_V792.c.
References CVT_V792_BIT_CLEAR_2_INDEX, CVT_V792_BIT_SET_2_INDEX, CVT_V792_BSC2_OVER_RANGE_DIS_MSK, cvt_write_reg(), FALSE, cvt_V792_data::m_common_data, TRACE, and TRUE.
BOOL cvt_V792_set_pedestal (cvt_V792_data * p_data, UINT8 value)
Set the pedestal value.
Writes the specified value to the Iped register
Parameters:
p_data Pointer to board data
value The value to set
Returns:
TRUE: Procedure successfully executed
Definition at line 1401 of file cvt_V792.c.
References CVT_V792_IPED_INDEX, cvt_write_reg(), FALSE, cvt_V792_data::m_common_data, TRACE, and TRUE.
BOOL cvt_V792_set_readout_mode (cvt_V792_data * p_data, BOOL bus_error_enable, BOOL block_end_enable, BOOL align64_enable)
Setups data readout mode parameters.
Setups the relevant parameters for data readout.
Parameters:
p_data Pointer to board data
bus_error_enable Enable bus error: the module is enabled to generate a Bus error to finish a block transfer.
block_end_enable Enable block end: the module sends all data to the CPU until the first EOB word (end of first event) is reached;
align64_enable Enable align 64: the module is enabled to add dummy word when the number of words is odd.
Returns:
TRUE: Procedure successfully executed
Definition at line 1310 of file cvt_V792.c.
References cvt_clear_bitmask_reg(), cvt_set_bitmask_reg(), CVT_V792_CONTROL_1_INDEX, CVT_V792_CTRL1_ALIGN64_MSK, CVT_V792_CTRL1_BERR_ENABLE_MSK, CVT_V792_CTRL1_BLKEND_MSK, FALSE, cvt_V792_data::m_common_data, TRACE, and TRUE.
BOOL cvt_V792_set_sliding_scale (cvt_V792_data * p_data, BOOL enable)
Setups the sliding scale feature.
Enable/ Disable sliding scale.
Parameters:
p_data Pointer to board data
enable Enable/disable the sliding scale
Returns:
TRUE: Procedure successfully executed
Definition at line 852 of file cvt_V792.c.
References CVT_V792_BIT_CLEAR_2_INDEX, CVT_V792_BIT_SET_2_INDEX, CVT_V792_BSC2_SLIDE_EN_MSK, cvt_write_reg(), FALSE, cvt_V792_data::m_common_data, TRACE, and TRUE.
BOOL cvt_V792_set_threshold (cvt_V792_data * p_data, cvt_V792_threshold_id threshold_id, UINT16 value)
Set the specified threshold register.
Writes the specified value to the specified threshold register. If threshold_id is CVT_V792_THRESHOLD_ALL every threshold will be setted to the same value.
Parameters:
p_data Pointer to board data
threshold_id The threshold to set. It must be a cvt_V792_threshold_id valid id.
value The value to set : Threshold value and Kill bit (CVT_V792_THRESHOLD_KILL_MSK) If the kill bit be isn't setted the channel will be disabled
Returns:
TRUE: Procedure successfully executed
See also:
cvt_V792_threshold_id
CVT_V792_THRESHOLD_KILL_MSK
< The board is V792A
< The board is V792N
< The board is V862A
< The board is V785A
< The board is V785N
< The board is V775A
< The board is V775N
Definition at line 613 of file cvt_V792.c.
References CVT_QTP_NUM_CHANNELS, CVT_V775_TYPE_A, CVT_V775_TYPE_N, CVT_V785_TYPE_A, CVT_V785_TYPE_N, CVT_V792_THRESHOLD_0, CVT_V792_THRESHOLD_0_INDEX, CVT_V792_THRESHOLD_1, CVT_V792_THRESHOLD_10, CVT_V792_THRESHOLD_11, CVT_V792_THRESHOLD_12, CVT_V792_THRESHOLD_13, CVT_V792_THRESHOLD_14, CVT_V792_THRESHOLD_15, CVT_V792_THRESHOLD_16, CVT_V792_THRESHOLD_17, CVT_V792_THRESHOLD_18, CVT_V792_THRESHOLD_19, CVT_V792_THRESHOLD_2, CVT_V792_THRESHOLD_20, CVT_V792_THRESHOLD_21, CVT_V792_THRESHOLD_22, CVT_V792_THRESHOLD_23, CVT_V792_THRESHOLD_24, CVT_V792_THRESHOLD_25, CVT_V792_THRESHOLD_26, CVT_V792_THRESHOLD_27, CVT_V792_THRESHOLD_28, CVT_V792_THRESHOLD_29, CVT_V792_THRESHOLD_3, CVT_V792_THRESHOLD_30, CVT_V792_THRESHOLD_31, CVT_V792_THRESHOLD_4, CVT_V792_THRESHOLD_5, CVT_V792_THRESHOLD_6, CVT_V792_THRESHOLD_7, CVT_V792_THRESHOLD_8, CVT_V792_THRESHOLD_9, CVT_V792_THRESHOLD_ALL, CVT_V792_TYPE_A, CVT_V792_TYPE_N, CVT_V862_TYPE_A, cvt_write_reg(), FALSE, cvt_V792_data::m_common_data, cvt_V792_data::m_type, TRACE1, and TRUE.
BOOL cvt_V792_set_zero_suppression (cvt_V792_data * p_data, BOOL enable, BOOL step_threshold, const UINT16 * thresholds_buff)
Setups the zero suppression feature.
Enable/ Disable zero suppression and setups other relevant parameters.
Parameters:
p_data Pointer to board data
enable Enable/disable the zero suppression (low threshold check).
step_threshold If setted the comparison is ADC CONVERTED VALUE < THRESHOLD VALUE x 2, otherwise ADC CONVERTED VALUE < THRESHOLD VALUE x 16
thresholds_buff The thresholds buffer: It must contain as many values as specified for the board type (CVT_QTP_NUM_CHANNELS). It may be NULL (e.g. when disabling this feature or the thresholds are already setted) The value consists of the threshold level and the kill bit (CVT_V792_THRESHOLD_KILL_MSK) If the kill bit be isn't setted the channel will be disabled
Returns:
TRUE: Procedure successfully executed
See also:
CVT_V792_THRESHOLD_KILL_MSK
< The board is V792A
< The board is V792N
< The board is V862A
< The board is V785A
< The board is V785N
< The board is V775A
< The board is V775N
Definition at line 868 of file cvt_V792.c.
References CVT_QTP_NUM_CHANNELS, CVT_V775_TYPE_A, CVT_V775_TYPE_N, CVT_V785_TYPE_A, CVT_V785_TYPE_N, CVT_V792_BIT_CLEAR_2_INDEX, CVT_V792_BIT_SET_2_INDEX, CVT_V792_BSC2_LOW_THR_DIS_MSK, CVT_V792_BSC2_STEP_TH_MSK, CVT_V792_THRESHOLD_0, CVT_V792_THRESHOLD_0_INDEX, CVT_V792_TYPE_A, CVT_V792_TYPE_N, CVT_V862_TYPE_A, cvt_write_reg(), FALSE, cvt_V792_data::m_common_data, cvt_V792_data::m_type, TRACE, TRACE1, and TRUE.
BOOL cvt_V792_single_shot_reset (cvt_V792_data * p_data)
Perfoms a single shot reset.
Writes a dummy value to the single shot reset register.
Parameters:
p_data Pointer to board data
Returns:
TRUE: Procedure successfully executed
Warning:
This register must be used very carefully and for debugging purposes only. In order to reset the board, it is recommended to use the Bit Set 1 Register
See also:
cvt_V792_set_bitmask_control_1
Definition at line 519 of file cvt_V792.c.
References CVT_V792_SINGLE_SHOT_RESET_INDEX, cvt_write_reg(), FALSE, cvt_V792_data::m_common_data, TRACE, and TRUE.
BOOL cvt_V792_software_reset (cvt_V792_data * p_data)
Performs a software reset.
Writes a dummy value into CVT_V792_SINGLE_SHOT_RESET register.
Parameters:
p_data Pointer to board data
Returns:
TRUE: Procedure successfully executed
Definition at line 1501 of file cvt_V792.c.
References CVT_V792_SINGLE_SHOT_RESET_INDEX, cvt_write_reg(), FALSE, cvt_V792_data::m_common_data, TRACE, and TRUE.
const char * cvt_V792_SW_rev (void)
Returns the SDK software release.
Returns:
const char*: The SDK revision string
Definition at line 1994 of file cvt_V792.c.