CAEN qtp SDK: cvt_V792.h File Reference
cvt_V792.h File Reference
V792 VME board definitions.
#include "cvt_common_defs.h"
#include "cvt_board_commons.h"
Data Structures
struct cvt_V792_data
V792 board data structure.
Defines
#define CVT_V792_THRESHOLD_NUM_A 32
Number of threshold registers for V792AA or V792AC.
#define CVT_V792_THRESHOLD_NUM_N 16
Number of threshold registers for V792NA or V792NC.
#define CVT_V792_USE_DATA_QUEUE 1
Enable/ disable V792 builtin data queue.
#define CVT_V792_QUEUE_SIZE_DWORD (1024*1024)
V792 data queue size.
#define CVT_V792_OUT_BUFFER_ADD 0x0000
Output buffer relative address.
#define CVT_V792_FW_REV_ADD 0x1000
Firmware Revision register relative address.
#define CVT_V792_GEO_ADDRESS_ADD 0x1002
Geo Address register relative address.
#define CVT_V792_MCST_CBLT_ADDRESS_ADD 0x1004
MCST/CBLT Address register relative address.
#define CVT_V792_BIT_SET_1_ADD 0x1006
Bit Set 1 register relative address.
#define CVT_V792_BIT_CLEAR_1_ADD 0x1008
Bit Clear 1 register relative address.
#define CVT_V792_INT_LEVEL_ADD 0x100A
Interrupt level register relative address.
#define CVT_V792_INT_VECTOR_ADD 0x100C
Interrupt vector register relative address.
#define CVT_V792_STATUS_1_ADD 0x100E
Status 1 register relative address.
#define CVT_V792_CONTROL_1_ADD 0x1010
Control 1 register relative address.
#define CVT_V792_ADER_HIGH_ADD 0x1012
Address decoder HIGH register relative address.
#define CVT_V792_ADER_LOW_ADD 0x1014
Address decoder LOW register relative address.
#define CVT_V792_SINGLE_SHOT_RESET_ADD 0x1016
Single Shot Reset register relative address.
#define CVT_V792_MCST_CBLT_CTRL_ADD 0x101A
MCST/CBLT control register relative address.
#define CVT_V792_EVENT_TRG_ADD 0x1020
Event trigger register relative address.
#define CVT_V792_STATUS_2_ADD 0x1022
Status 2 register relative address.
#define CVT_V792_EVENT_COUNTER_LOW_ADD 0x1024
Event counter low register relative address.
#define CVT_V792_EVENT_COUNTER_HIGH_ADD 0x1026
Event counter high register relative address.
#define CVT_V792_INC_EVENT_ADD 0x1028
Increment Event register relative address.
#define CVT_V792_INC_OFFSET_ADD 0x102A
Increment Offset register relative address.
#define CVT_V792_LOAD_TEST_ADD 0x102C
Load Test register relative address.
#define CVT_V792_FCLR_WND_ADD 0x102E
FCLR window register relative address.
#define CVT_V792_BIT_SET_2_ADD 0x1032
Bit Set 2 register relative address.
#define CVT_V792_BIT_CLEAR_2_ADD 0x1034
Bit Clear 2 register relative address.
#define CVT_V792_W_MEMORY_TEST_ADDRESS_ADD 0x1036
W Memory Test Address register relative address.
#define CVT_V792_MEMORY_TEST_WORD_HIGH_ADD 0x1038
Memory Test Word High register relative address.
#define CVT_V792_MEMORY_TEST_WORD_LOW_ADD 0x103A
Memory Test Word Low register relative address.
#define CVT_V792_CRATE_SELECT_ADD 0x103C
Crate select register relative address.
#define CVT_V792_TEST_EVENT_WRITE_ADD 0x103E
Test Event register Write relative address.
#define CVT_V792_EVENT_COUNT_RESET_ADD 0x1040
Event Counter Reset register relative address.
#define CVT_V792_IPED_ADD 0x1060
Iped register relative address.
#define CVT_V792_R_TEST_ADDRESS_ADD 0x1064
R Test Address register relative address.
#define CVT_V792_SW_COMM_ADD 0x1068
SW Comm register relative address.
#define CVT_V792_SLIDE_CONSTANT_ADD 0x106A
Sliding constant register relative address.
#define CVT_V792_AAD_ADD 0x1070
AAD register relative address.
#define CVT_V792_BAD_ADD 0x1072
BAD register relative address.
#define CVT_V792_THRESHOLD_0_ADD 0x1080
Threshold 0 register relative address.
#define CVT_V792_THRESHOLD_1_ADD 0x1082
Threshold 1 register relative address.
#define CVT_V792_THRESHOLD_2_ADD 0x1084
Threshold 2 register relative address.
#define CVT_V792_THRESHOLD_3_ADD 0x1086
Threshold 3 register relative address.
#define CVT_V792_THRESHOLD_4_ADD 0x1088
Threshold 4 register relative address.
#define CVT_V792_THRESHOLD_5_ADD 0x108A
Threshold 5 register relative address.
#define CVT_V792_THRESHOLD_6_ADD 0x108C
Threshold 6 register relative address.
#define CVT_V792_THRESHOLD_7_ADD 0x108E
Threshold 7 register relative address.
#define CVT_V792_THRESHOLD_8_ADD 0x1090
Threshold 8 register relative address.
#define CVT_V792_THRESHOLD_9_ADD 0x1092
Threshold 9 register relative address.
#define CVT_V792_THRESHOLD_10_ADD 0x1094
Threshold 10 register relative address.
#define CVT_V792_THRESHOLD_11_ADD 0x1096
Threshold 11 register relative address.
#define CVT_V792_THRESHOLD_12_ADD 0x1098
Threshold 12 register relative address.
#define CVT_V792_THRESHOLD_13_ADD 0x109A
Threshold 13 register relative address.
#define CVT_V792_THRESHOLD_14_ADD 0x109C
Threshold 14 register relative address.
#define CVT_V792_THRESHOLD_15_ADD 0x109E
Threshold 15 register relative address.
#define CVT_V792_THRESHOLD_16_ADD 0x10A0
Threshold 16 register relative address.
#define CVT_V792_THRESHOLD_17_ADD 0x10A2
Threshold 17 register relative address.
#define CVT_V792_THRESHOLD_18_ADD 0x10A4
Threshold 18 register relative address.
#define CVT_V792_THRESHOLD_19_ADD 0x10A6
Threshold 19 register relative address.
#define CVT_V792_THRESHOLD_20_ADD 0x10A8
Threshold 20 register relative address.
#define CVT_V792_THRESHOLD_21_ADD 0x10AA
Threshold 21 register relative address.
#define CVT_V792_THRESHOLD_22_ADD 0x10AC
Threshold 22 register relative address.
#define CVT_V792_THRESHOLD_23_ADD 0x10AE
Threshold 23 register relative address.
#define CVT_V792_THRESHOLD_24_ADD 0x10B0
Threshold 24 register relative address.
#define CVT_V792_THRESHOLD_25_ADD 0x10B2
Threshold 25 register relative address.
#define CVT_V792_THRESHOLD_26_ADD 0x10B4
Threshold 26 register relative address.
#define CVT_V792_THRESHOLD_27_ADD 0x10B6
Threshold 27 register relative address.
#define CVT_V792_THRESHOLD_28_ADD 0x10B8
Threshold 28 register relative address.
#define CVT_V792_THRESHOLD_29_ADD 0x10BA
Threshold 29 register relative address.
#define CVT_V792_THRESHOLD_30_ADD 0x10BC
Threshold 30 register relative address.
#define CVT_V792_THRESHOLD_31_ADD 0x10BE
Threshold 31 register relative address.
#define CVT_V792_ROM_OUI_2_ADD 0x8026
Manufacturer identifier (IEEE OUI) (MSB) relative address.
#define CVT_V792_ROM_OUI_1_ADD 0x802A
Manufacturer identifier (IEEE OUI) relative address.
#define CVT_V792_ROM_OUI_0_ADD 0x802E
Manufacturer identifier (IEEE OUI) (LSB) relative address.
#define CVT_V792_ROM_VERSION_ADD 0x8032
Purchased version of the Mod.V792 relative address.
#define CVT_V792_ROM_BOARD_ID_2_ADD 0x8036
Board identifier (MSB) relative address.
#define CVT_V792_ROM_BOARD_ID_1_ADD 0x803A
Board identifier relative address.
#define CVT_V792_ROM_BOARD_ID_0_ADD 0x803E
Board identifier (LSB) relative address.
#define CVT_V792_ROM_REVISION_ADD 0x804E
Hardware revision identifier relative address.
#define CVT_V792_ROM_SERIAL_1_ADD 0x8F02
Serial number (MSB) relative address.
#define CVT_V792_ROM_SERIAL_0_ADD 0x8F06
Serial number (LSB) relative address.
#define CVT_V792_OUT_BUFFER_DATA_SIZE cvD64
Output buffer data size.
#define CVT_V792_FW_REV_DATA_SIZE cvD16
Firmware Revision register data size.
#define CVT_V792_GEO_ADDRESS_DATA_SIZE cvD16
Geo Address register data size.
#define CVT_V792_MCST_CBLT_ADDRESS_DATA_SIZE cvD16
MCST/CBLT Address register data size.
#define CVT_V792_BIT_SET_1_DATA_SIZE cvD16
Bit Set 1 register data size.
#define CVT_V792_BIT_CLEAR_1_DATA_SIZE cvD16
Bit Clear 1 register data size.
#define CVT_V792_INT_LEVEL_DATA_SIZE cvD16
Interrupt level register data size.
#define CVT_V792_INT_VECTOR_DATA_SIZE cvD16
Interrupt vector register data size.
#define CVT_V792_STATUS_1_DATA_SIZE cvD16
Status 1 register data size.
#define CVT_V792_CONTROL_1_DATA_SIZE cvD16
Control 1 register data size.
#define CVT_V792_ADER_HIGH_DATA_SIZE cvD16
Address decoder HIGH register data size.
#define CVT_V792_ADER_LOW_DATA_SIZE cvD16
Address decoder LOW register data size.
#define CVT_V792_SINGLE_SHOT_RESET_DATA_SIZE cvD16
Single Shot Reset register data size.
#define CVT_V792_MCST_CBLT_CTRL_DATA_SIZE cvD16
MCST/CBLT control register data size.
#define CVT_V792_EVENT_TRG_DATA_SIZE cvD16
Event trigger register data size.
#define CVT_V792_STATUS_2_DATA_SIZE cvD16
Status 2 register data size.
#define CVT_V792_EVENT_COUNTER_LOW_DATA_SIZE cvD16
Event counter low register data size.
#define CVT_V792_EVENT_COUNTER_HIGH_DATA_SIZE cvD16
Event counter high register data size.
#define CVT_V792_INC_EVENT_DATA_SIZE cvD16
Increment Event register data size.
#define CVT_V792_INC_OFFSET_DATA_SIZE cvD16
Increment Offset register data size.
#define CVT_V792_LOAD_TEST_DATA_SIZE cvD16
Load Test register data size.
#define CVT_V792_FCLR_WND_DATA_SIZE cvD16
FCLR window register data size.
#define CVT_V792_BIT_SET_2_DATA_SIZE cvD16
Bit Set 2 register data size.
#define CVT_V792_BIT_CLEAR_2_DATA_SIZE cvD16
Bit Clear 2 register data size.
#define CVT_V792_W_MEMORY_TEST_ADDRESS_DATA_SIZE cvD16
W Memory Test Address register data size.
#define CVT_V792_MEMORY_TEST_WORD_HIGH_DATA_SIZE cvD16
Memory Test Word High register data size.
#define CVT_V792_MEMORY_TEST_WORD_LOW_DATA_SIZE cvD16
Memory Test Word Low register data size.
#define CVT_V792_CRATE_SELECT_DATA_SIZE cvD16
Crate select register data size.
#define CVT_V792_TEST_EVENT_WRITE_DATA_SIZE cvD16
Test Event Write register data size.
#define CVT_V792_EVENT_COUNT_RESET_DATA_SIZE cvD16
Event Counter Reset register data size.
#define CVT_V792_IPED_DATA_SIZE cvD16
Iped register data size.
#define CVT_V792_R_TEST_ADDRESS_DATA_SIZE cvD16
R Test Address register data size.
#define CVT_V792_SW_COMM_DATA_SIZE cvD16
SW Comm register data size.
#define CVT_V792_SLIDE_CONSTANT_DATA_SIZE cvD16
Sliding constant register data size.
#define CVT_V792_AAD_DATA_SIZE cvD16
AAD register data size.
#define CVT_V792_BAD_DATA_SIZE cvD16
BAD register data size.
#define CVT_V792_THRESHOLD_DATA_SIZE cvD16
Threshold register data size.
#define CVT_V792_ROM_OUI_2_DATA_SIZE cvD16
Manufacturer identifier (IEEE OUI) (MSB) data size.
#define CVT_V792_ROM_OUI_1_DATA_SIZE cvD16
Manufacturer identifier (IEEE OUI) data size.
#define CVT_V792_ROM_OUI_0_DATA_SIZE cvD16
Manufacturer identifier (IEEE OUI) (LSB) data size.
#define CVT_V792_ROM_VERSION_DATA_SIZE cvD16
Purchased version of the Mod.V792 data size.
#define CVT_V792_ROM_BOARD_ID_2_DATA_SIZE cvD16
Board identifier (MSB) data size.
#define CVT_V792_ROM_BOARD_ID_1_DATA_SIZE cvD16
Board identifier data size.
#define CVT_V792_ROM_BOARD_ID_0_DATA_SIZE cvD16
Board identifier (LSB) data size.
#define CVT_V792_ROM_REVISION_DATA_SIZE cvD16
Hardware revision identifier data size.
#define CVT_V792_ROM_SERIAL_1_DATA_SIZE cvD16
Serial number (MSB) data size.
#define CVT_V792_ROM_SERIAL_0_DATA_SIZE cvD16
Serial number (LSB) data size.
#define CVT_V792_OUT_BUFFER_AM cvA32_S_MBLT
Output buffer address modifier.
#define CVT_V792_FW_REV_AM cvA32_S_DATA
Firmware Revision register address modifier.
#define CVT_V792_GEO_ADDRESS_AM cvA32_S_DATA
Geo Address register address modifier.
#define CVT_V792_MCST_CBLT_ADDRESS_AM cvA32_S_DATA
MCST/CBLT Address register address modifier.
#define CVT_V792_BIT_SET_1_AM cvA32_S_DATA
Bit Set 1 register address modifier.
#define CVT_V792_BIT_CLEAR_1_AM cvA32_S_DATA
Bit Clear 1 register address modifier.
#define CVT_V792_INT_LEVEL_AM cvA32_S_DATA
Interrupt level register address modifier.
#define CVT_V792_INT_VECTOR_AM cvA32_S_DATA
Interrupt vector register address modifier.
#define CVT_V792_STATUS_1_AM cvA32_S_DATA
Status 1 register address modifier.
#define CVT_V792_CONTROL_1_AM cvA32_S_DATA
Control 1 register address modifier.
#define CVT_V792_ADER_HIGH_AM cvA32_S_DATA
Address decoder HIGH register address modifier.
#define CVT_V792_ADER_LOW_AM cvA32_S_DATA
Address decoder LOW register address modifier.
#define CVT_V792_SINGLE_SHOT_RESET_AM cvA32_S_DATA
Single Shot Reset register address modifier.
#define CVT_V792_MCST_CBLT_CTRL_AM cvA32_S_DATA
MCST/CBLT control register address modifier.
#define CVT_V792_EVENT_TRG_AM cvA32_S_DATA
Event trigger register address modifier.
#define CVT_V792_STATUS_2_AM cvA32_S_DATA
Status 2 register address modifier.
#define CVT_V792_EVENT_COUNTER_LOW_AM cvA32_S_DATA
Event counter low register address modifier.
#define CVT_V792_EVENT_COUNTER_HIGH_AM cvA32_S_DATA
Event counter high register address modifier.
#define CVT_V792_INC_EVENT_AM cvA32_S_DATA
Increment Event register address modifier.
#define CVT_V792_INC_OFFSET_AM cvA32_S_DATA
Increment Offset register address modifier.
#define CVT_V792_LOAD_TEST_AM cvA32_S_DATA
Load Test register address modifier.
#define CVT_V792_FCLR_WND_AM cvA32_S_DATA
FCLR window register address modifier.
#define CVT_V792_BIT_SET_2_AM cvA32_S_DATA
Bit Set 2 register address modifier.
#define CVT_V792_BIT_CLEAR_2_AM cvA32_S_DATA
Bit Clear 2 register address modifier.
#define CVT_V792_W_MEMORY_TEST_ADDRESS_AM cvA32_S_DATA
W Memory Test Address register address modifier.
#define CVT_V792_MEMORY_TEST_WORD_HIGH_AM cvA32_S_DATA
Memory Test Word High register address modifier.
#define CVT_V792_MEMORY_TEST_WORD_LOW_AM cvA32_S_DATA
Memory Test Word Low register address modifier.
#define CVT_V792_CRATE_SELECT_AM cvA32_S_DATA
Crate select register address modifier.
#define CVT_V792_TEST_EVENT_WRITE_AM cvA32_S_DATA
Test Event Write register address modifier.
#define CVT_V792_EVENT_COUNT_RESET_AM cvA32_S_DATA
Event Counter Reset register address modifier.
#define CVT_V792_IPED_AM cvA32_S_DATA
Iped register address modifier.
#define CVT_V792_R_TEST_ADDRESS_AM cvA32_S_DATA
R Test Address register address modifier.
#define CVT_V792_SW_COMM_AM cvA32_S_DATA
SW Comm register address modifier.
#define CVT_V792_SLIDE_CONSTANT_AM cvA32_S_DATA
Sliding constant register address modifier.
#define CVT_V792_AAD_AM cvA32_S_DATA
AAD register address modifier.
#define CVT_V792_BAD_AM cvA32_S_DATA
BAD register address modifier.
#define CVT_V792_THRESHOLD_AM cvA32_S_DATA
Threshold register address modifier.
#define CVT_V792_ROM_OUI_2_AM cvA32_S_DATA
Manufacturer identifier (IEEE OUI) (MSB) address modifier.
#define CVT_V792_ROM_OUI_1_AM cvA32_S_DATA
Manufacturer identifier (IEEE OUI) address modifier.
#define CVT_V792_ROM_OUI_0_AM cvA32_S_DATA
Manufacturer identifier (IEEE OUI) (LSB) address modifier.
#define CVT_V792_ROM_VERSION_AM cvA32_S_DATA
Purchased version of the Mod.V792 address modifier.
#define CVT_V792_ROM_BOARD_ID_2_AM cvA32_S_DATA
Board identifier (MSB) address modifier.
#define CVT_V792_ROM_BOARD_ID_1_AM cvA32_S_DATA
Board identifier address modifier.
#define CVT_V792_ROM_BOARD_ID_0_AM cvA32_S_DATA
Board identifier (LSB) address modifier.
#define CVT_V792_ROM_REVISION_AM cvA32_S_DATA
Hardware revision identifier address modifier.
#define CVT_V792_ROM_SERIAL_1_AM cvA32_S_DATA
Serial number (MSB) address modifier.
#define CVT_V792_ROM_SERIAL_0_AM cvA32_S_DATA
Serial number (LSB) address modifier.
#define CVT_V792_STS2_PIGGY_BACK_TYPE_MSK 0x00F0
#define CVT_V792_GET_PIGGY_BACK_TYPE(reg) ((((UINT16)reg)& CVT_V792_STS2_PIGGY_BACK_TYPE_MSK)>> 4)
Extract the piggy back type from UINT16 value.
#define CVT_V792_SET_PIGGY_BACK_TYPE(reg) reg= (((UINT16)reg)& ~CVT_V792_STS2_PIGGY_BACK_TYPE_MSK)| ((((UINT16)value)<< 4)&CVT_V792_STS2_PIGGY_BACK_TYPE_MSK)
Sets the piggy back type into UINT16 value.
#define CVT_QTP_DATA_TYPE_MSK 0x07000000
Data type bit masks.
#define CVT_QTP_HEADER 0x02000000
Header data type.
#define CVT_QTP_EOB 0x04000000
End of block data type.
#define CVT_QTP_DATUM 0x00000000
Datum data type.
#define CVT_QTP_NOT_VALID_DATUM 0x06000000
Not valid datum data type.
#define CVT_QTP_HDR_GEO_MSK 0xf8000000
The header GEO address msk.
#define CVT_QTP_HDR_CRATE_MSK 0x00ff0000
The header crate msk.
#define CVT_QTP_HDR_CH_COUNT_MSK 0x00003f00
The header channel count msk.
#define CVT_QTP_EOB_GEO_MSK 0xf8000000
The EOB GEO address msk.
#define CVT_QTP_EOB_MAX_EVENT_COUNT (0x00ffffff+ 1)
The EOB Max Event count.
#define CVT_QTP_EOB_EVENT_COUNT_MSK 0x00ffffff
The EOB Event count msk.
#define CVT_V792_DATUM_GEO_MSK 0xf8000000
The DATUM GEO address msk for V792.
#define CVT_V792_DATUM_CH_MSK 0x001f0000
The DATUM channel msk for V792 (bit 0x00010000 is always zero for V792N).
#define CVT_V792_DATUM_UN_MSK 0x00002000
The DATUM Under threshold msk for V792.
#define CVT_V792_DATUM_OV_MSK 0x00001000
The DATUM Overflow msk for V792.
#define CVT_V792_DATUM_ADC_MSK 0x00000fff
The DATUM ADC msk for V792.
#define CVT_V785_DATUM_GEO_MSK 0xf8000000
The DATUM GEO address msk for V785.
#define CVT_V785_DATUM_CH_MSK 0x001f0000
The DATUM channel msk for V785 (bit 0x00010000 is always zero for V785N).
#define CVT_V785_DATUM_UN_MSK 0x00002000
The DATUM Under threshold msk for V785.
#define CVT_V785_DATUM_OV_MSK 0x00001000
The DATUM Overflow msk for V785.
#define CVT_V785_DATUM_ADC_MSK 0x00000fff
The DATUM ADC msk for V785.
#define CVT_V775_DATUM_GEO_MSK 0xf8000000
The DATUM GEO address msk for V775.
#define CVT_V775_DATUM_CH_MSK 0x001f0000
The DATUM channel msk for V775 (bit 0x00010000 is always zero for V775N).
#define CVT_V775_DATUM_VD_MSK 0x00004000
The DATUM valid bit msk for V775.
#define CVT_V775_DATUM_UN_MSK 0x00002000
The DATUM Under threshold msk for V775.
#define CVT_V775_DATUM_OV_MSK 0x00001000
The DATUM Overflow msk for V775.
#define CVT_V775_DATUM_ADC_MSK 0x00000fff
The DATUM ADC msk for V775.
#define CVT_V862_DATUM_GEO_MSK 0xf8000000
The DATUM GEO address msk for V862.
#define CVT_V862_DATUM_CH_MSK 0x001f0000
The DATUM channel msk for V862.
#define CVT_V862_DATUM_UN_MSK 0x00002000
The DATUM Under threshold msk for V862.
#define CVT_V862_DATUM_OV_MSK 0x00001000
The DATUM Overflow msk for V862.
#define CVT_V862_DATUM_ADC_MSK 0x00000fff
The DATUM ADC msk for V862.
#define CVT_V1785_DATUM_GEO_MSK 0xf8000000
The DATUM GEO address msk for V1785.
#define CVT_V1785_DATUM_CH_MSK 0x001c0000
The DATUM channel msk for V1785.
#define CVT_V1785_DATUM_RG_MSK 0x00020000
The DATUM range msk for V1785.
#define CVT_V1785_DATUM_UN_MSK 0x00002000
The DATUM Under threshold msk for V1785.
#define CVT_V1785_DATUM_OV_MSK 0x00001000
The DATUM Overflow msk for V1785.
#define CVT_V1785_DATUM_ADC_MSK 0x00000fff
The DATUM ADC msk for V1785.
#define CVT_V965_DATUM_GEO_MSK 0xf8000000
The DATUM GEO address msk for V965.
#define CVT_V965_DATUM_CH_MSK 0x001e0000
The DATUM channel msk for V965.
#define CVT_V965A_DATUM_CH_MSK 0x001c0000
The DATUM channel msk for V965A.
#define CVT_V965_DATUM_RG_MSK 0x00010000
The DATUM range msk for V965.
#define CVT_V965A_DATUM_RG_MSK 0x00020000
The DATUM range msk for V965A.
#define CVT_V965_DATUM_UN_MSK 0x00002000
The DATUM Under threshold msk for V965.
#define CVT_V965_DATUM_OV_MSK 0x00001000
The DATUM Overflow msk for V965.
#define CVT_V965_DATUM_ADC_MSK 0x00000fff
The DATUM ADC msk for V965.
#define CVT_QTP_IS_HEADER(data) ((data& CVT_QTP_DATA_TYPE_MSK)== CVT_QTP_HEADER)
Check if Header data type.
#define CVT_QTP_IS_EOB(data) ((data& CVT_QTP_DATA_TYPE_MSK)== CVT_QTP_EOB)
Check if End of block data type.
#define CVT_QTP_IS_DATUM(data) ((data& CVT_QTP_DATA_TYPE_MSK)== CVT_QTP_DATUM)
Check if Datum data type.
#define CVT_QTP_IS_NOT_VALID_DATUM(data) ((data& CVT_QTP_DATA_TYPE_MSK)== CVT_QTP_NOT_VALID_DATUM)
Check if Not valid datum data type.
#define CVT_QTP_GET_HDR_GEO(data) ((UINT32)((((UINT32)data)& CVT_QTP_HDR_GEO_MSK)>>27))
Gets the header GEO address.
#define CVT_QTP_GET_HDR_CRATE(data) ((UINT32)((((UINT32)data)& CVT_QTP_HDR_CRATE_MSK)>>16))
Gets the header crate.
#define CVT_QTP_GET_HDR_CH_COUNT(data) ((UINT32)((((UINT32)data)& CVT_QTP_HDR_CH_COUNT_MSK)>>8))
Gets the header channel count.
#define CVT_QTP_GET_EOB_GEO(data) ((UINT32)((((UINT32)data)& CVT_QTP_EOB_GEO_MSK)>>27))
Gets the EOB GEO address.
#define CVT_QTP_GET_EOB_EVENT_COUNT(data) ((UINT32)(((UINT32)data)& CVT_QTP_EOB_EVENT_COUNT_MSK))
Gets the EOB Event count.
#define CVT_V792_GET_DATUM_GEO(data) ((UINT32)((((UINT32)data)& CVT_V792_DATUM_GEO_MSK)>>27))
Gets the DATUM GEO address for V792.
#define CVT_V792_GET_DATUM_UN(data) ((UINT32)((((UINT32)data)& CVT_V792_DATUM_UN_MSK)>>13))
Gets the DATUM Under threshold for V792.
#define CVT_V792_GET_DATUM_OV(data) ((UINT32)((((UINT32)data)& CVT_V792_DATUM_OV_MSK)>>12))
Gets the DATUM Overflow for V792.
#define CVT_V792_GET_DATUM_ADC(data) ((UINT32)(((UINT32)data)& CVT_V792_DATUM_ADC_MSK))
Gets the DATUM ADC for V792.
#define CVT_V792N_GET_DATUM_CH(data) ((UINT32)((((UINT32)data)& CVT_V792_DATUM_CH_MSK)>>17))
Gets the DATUM channel for V792N.
#define CVT_V792A_GET_DATUM_CH(data) ((UINT32)((((UINT32)data)& CVT_V792_DATUM_CH_MSK)>>16))
Gets the DATUM channel for V792A.
#define CVT_V785_GET_DATUM_GEO(data) ((UINT32)((((UINT32)data)& CVT_V785_DATUM_GEO_MSK)>>27))
Gets the DATUM GEO address for V785.
#define CVT_V785_GET_DATUM_UN(data) ((UINT32)((((UINT32)data)& CVT_V785_DATUM_UN_MSK)>>13))
Gets the DATUM Under threshold for V785.
#define CVT_V785_GET_DATUM_OV(data) ((UINT32)((((UINT32)data)& CVT_V785_DATUM_OV_MSK)>>12))
Gets the DATUM Overflow for V785.
#define CVT_V785_GET_DATUM_ADC(data) ((UINT32)(((UINT32)data)& CVT_V785_DATUM_ADC_MSK))
Gets the DATUM ADC for V785.
#define CVT_V785N_GET_DATUM_CH(data) ((UINT32)((((UINT32)data)& CVT_V785_DATUM_CH_MSK)>>17))
Gets the DATUM channel for V785N.
#define CVT_V785A_GET_DATUM_CH(data) ((UINT32)((((UINT32)data)& CVT_V785_DATUM_CH_MSK)>>16))
Gets the DATUM channel for V785A.
#define CVT_V775_GET_DATUM_GEO(data) ((UINT32)((((UINT32)data)& CVT_V775_DATUM_GEO_MSK)>>27))
Gets the DATUM GEO address for V775.
#define CVT_V775_GET_DATUM_VD(data) ((UINT32)((((UINT32)data)& CVT_V775_DATUM_VD_MSK)>>14))
Gets the DATUM Valid bit for V775.
#define CVT_V775_GET_DATUM_UN(data) ((UINT32)((((UINT32)data)& CVT_V775_DATUM_UN_MSK)>>13))
Gets the DATUM Under threshold for V775.
#define CVT_V775_GET_DATUM_OV(data) ((UINT32)((((UINT32)data)& CVT_V775_DATUM_OV_MSK)>>12))
Gets the DATUM Overflow for V775.
#define CVT_V775_GET_DATUM_ADC(data) ((UINT32)(((UINT32)data)& CVT_V775_DATUM_ADC_MSK))
Gets the DATUM ADC for V775.
#define CVT_V775N_GET_DATUM_CH(data) ((UINT32)((((UINT32)data)& CVT_V775_DATUM_CH_MSK)>>17))
Gets the DATUM channel for V775N.
#define CVT_V775A_GET_DATUM_CH(data) ((UINT32)((((UINT32)data)& CVT_V775_DATUM_CH_MSK)>>16))
Gets the DATUM channel for V775A.
#define CVT_V862_GET_DATUM_GEO(data) ((UINT32)((((UINT32)data)& CVT_V862_DATUM_GEO_MSK)>>27))
Gets the DATUM GEO address for V862.
#define CVT_V862_GET_DATUM_UN(data) ((UINT32)((((UINT32)data)& CVT_V862_DATUM_UN_MSK)>>13))
Gets the DATUM Under threshold for V862.
#define CVT_V862_GET_DATUM_OV(data) ((UINT32)((((UINT32)data)& CVT_V862_DATUM_OV_MSK)>>12))
Gets the DATUM Overflow for V862.
#define CVT_V862_GET_DATUM_ADC(data) ((UINT32)(((UINT32)data)& CVT_V862_DATUM_ADC_MSK))
Gets the DATUM ADC for V862.
#define CVT_V862_GET_DATUM_CH(data) ((UINT32)((((UINT32)data)& CVT_V862_DATUM_CH_MSK)>>16))
Gets the DATUM channel for V862.
#define CVT_V1785_GET_DATUM_GEO(data) ((UINT32)((((UINT32)data)& CVT_V1785_DATUM_GEO_MSK)>>27))
Gets the DATUM GEO address for V1785.
#define CVT_V1785_GET_DATUM_RG(data) ((UINT32)((((UINT32)data)& CVT_V1785_DATUM_RG_MSK)>>17))
Gets the DATUM range for V1785.
#define CVT_V1785_GET_DATUM_UN(data) ((UINT32)((((UINT32)data)& CVT_V1785_DATUM_UN_MSK)>>13))
Gets the DATUM Under threshold for V1785.
#define CVT_V1785_GET_DATUM_OV(data) ((UINT32)((((UINT32)data)& CVT_V1785_DATUM_OV_MSK)>>12))
Gets the DATUM Overflow for V1785.
#define CVT_V1785_GET_DATUM_ADC(data) ((UINT32)(((UINT32)data)& CVT_V1785_DATUM_ADC_MSK))
Gets the DATUM ADC for V1785.
#define CVT_V1785_GET_DATUM_CH(data) ((UINT32)((((UINT32)data)& CVT_V1785_DATUM_CH_MSK)>>18))
Gets the DATUM channel for V1785.
#define CVT_V965_GET_DATUM_GEO(data) ((UINT32)((((UINT32)data)& CVT_V965_DATUM_GEO_MSK)>>27))
Gets the DATUM GEO address for V965.
#define CVT_V965_GET_DATUM_RG(data) ((UINT32)((((UINT32)data)& CVT_V965_DATUM_RG_MSK)>>16))
Gets the DATUM range for V965.
#define CVT_V965A_GET_DATUM_RG(data) ((UINT32)((((UINT32)data)& CVT_V965A_DATUM_RG_MSK)>>17))
Gets the DATUM range for V965A.
#define CVT_V965_GET_DATUM_UN(data) ((UINT32)((((UINT32)data)& CVT_V965_DATUM_UN_MSK)>>13))
Gets the DATUM Under threshold for V965.
#define CVT_V965_GET_DATUM_OV(data) ((UINT32)((((UINT32)data)& CVT_V965_DATUM_OV_MSK)>>12))
Gets the DATUM Overflow for V965.
#define CVT_V965_GET_DATUM_ADC(data) ((UINT32)(((UINT32)data)& CVT_V965_DATUM_ADC_MSK))
Gets the DATUM ADC for V965.
#define CVT_V965_GET_DATUM_CH(data) ((UINT32)((((UINT32)data)& CVT_V965_DATUM_CH_MSK)>>17))
Gets the DATUM channel for V965.
#define CVT_V965A_GET_DATUM_CH(data) ((UINT32)((((UINT32)data)& CVT_V965A_DATUM_CH_MSK)>>18))
Gets the DATUM channel for V965A.
Enumerations
enum CVT_QTP_TYPES {
CVT_V792_TYPE_A, CVT_V792_TYPE_N, CVT_V862_TYPE_A, CVT_V965,
CVT_V965_TYPE_A, CVT_V785_TYPE_A, CVT_V785_TYPE_N, CVT_V1785,
CVT_V775_TYPE_A, CVT_V775_TYPE_N
}
The QTP board type.
enum CVT_V792_REG_INDEX {
CVT_V792_OUT_BUFFER_INDEX, CVT_V792_FW_REV_INDEX, CVT_V792_GEO_ADDRESS_INDEX, CVT_V792_MCST_CBLT_ADDRESS_INDEX,
CVT_V792_BIT_SET_1_INDEX, CVT_V792_BIT_CLEAR_1_INDEX, CVT_V792_INT_LEVEL_INDEX, CVT_V792_INT_VECTOR_INDEX,
CVT_V792_STATUS_1_INDEX, CVT_V792_CONTROL_1_INDEX, CVT_V792_ADER_HIGH_INDEX, CVT_V792_ADER_LOW_INDEX,
CVT_V792_SINGLE_SHOT_RESET_INDEX, CVT_V792_MCST_CBLT_CTRL_INDEX, CVT_V792_EVENT_TRG_INDEX, CVT_V792_STATUS_2_INDEX,
CVT_V792_EVENT_COUNTER_LOW_INDEX, CVT_V792_EVENT_COUNTER_HIGH_INDEX, CVT_V792_INC_EVENT_INDEX, CVT_V792_INC_OFFSET_INDEX,
CVT_V792_LOAD_TEST_INDEX, CVT_V792_FCLR_WND_INDEX, CVT_V792_BIT_SET_2_INDEX, CVT_V792_BIT_CLEAR_2_INDEX,
CVT_V792_W_MEMORY_TEST_ADDRESS_INDEX, CVT_V792_MEMORY_TEST_WORD_HIGH_INDEX, CVT_V792_MEMORY_TEST_WORD_LOW_INDEX, CVT_V792_CRATE_SELECT_INDEX,
CVT_V792_TEST_EVENT_WRITE_INDEX, CVT_V792_EVENT_COUNT_RESET_INDEX, CVT_V792_IPED_INDEX, CVT_V792_R_TEST_ADDRESS_INDEX,
CVT_V792_SW_COMM_INDEX, CVT_V792_SLIDE_CONSTANT_INDEX, CVT_V792_AAD_INDEX, CVT_V792_BAD_INDEX,
CVT_V792_THRESHOLD_0_INDEX, CVT_V792_THRESHOLD_1_INDEX, CVT_V792_THRESHOLD_2_INDEX, CVT_V792_THRESHOLD_3_INDEX,
CVT_V792_THRESHOLD_4_INDEX, CVT_V792_THRESHOLD_5_INDEX, CVT_V792_THRESHOLD_6_INDEX, CVT_V792_THRESHOLD_7_INDEX,
CVT_V792_THRESHOLD_8_INDEX, CVT_V792_THRESHOLD_9_INDEX, CVT_V792_THRESHOLD_10_INDEX, CVT_V792_THRESHOLD_11_INDEX,
CVT_V792_THRESHOLD_12_INDEX, CVT_V792_THRESHOLD_13_INDEX, CVT_V792_THRESHOLD_14_INDEX, CVT_V792_THRESHOLD_15_INDEX,
CVT_V792_THRESHOLD_16_INDEX, CVT_V792_THRESHOLD_17_INDEX, CVT_V792_THRESHOLD_18_INDEX, CVT_V792_THRESHOLD_19_INDEX,
CVT_V792_THRESHOLD_20_INDEX, CVT_V792_THRESHOLD_21_INDEX, CVT_V792_THRESHOLD_22_INDEX, CVT_V792_THRESHOLD_23_INDEX,
CVT_V792_THRESHOLD_24_INDEX, CVT_V792_THRESHOLD_25_INDEX, CVT_V792_THRESHOLD_26_INDEX, CVT_V792_THRESHOLD_27_INDEX,
CVT_V792_THRESHOLD_28_INDEX, CVT_V792_THRESHOLD_29_INDEX, CVT_V792_THRESHOLD_30_INDEX, CVT_V792_THRESHOLD_31_INDEX,
CVT_V792_ROM_OUI_2_INDEX, CVT_V792_ROM_OUI_1_INDEX, CVT_V792_ROM_OUI_0_INDEX, CVT_V792_ROM_VERSION_INDEX,
CVT_V792_ROM_BOARD_ID_2_INDEX, CVT_V792_ROM_BOARD_ID_1_INDEX, CVT_V792_ROM_BOARD_ID_0_INDEX, CVT_V792_ROM_REVISION_INDEX,
CVT_V792_ROM_SERIAL_1_INDEX, CVT_V792_ROM_SERIAL_0_INDEX
}
The registers indexes.
enum cvt_V792_threshold_id {
CVT_V792_THRESHOLD_ALL = -1, CVT_V792_THRESHOLD_0 = 0, CVT_V792_THRESHOLD_1, CVT_V792_THRESHOLD_2,
CVT_V792_THRESHOLD_3, CVT_V792_THRESHOLD_4, CVT_V792_THRESHOLD_5, CVT_V792_THRESHOLD_6,
CVT_V792_THRESHOLD_7, CVT_V792_THRESHOLD_8, CVT_V792_THRESHOLD_9, CVT_V792_THRESHOLD_10,
CVT_V792_THRESHOLD_11, CVT_V792_THRESHOLD_12, CVT_V792_THRESHOLD_13, CVT_V792_THRESHOLD_14,
CVT_V792_THRESHOLD_15, CVT_V792_THRESHOLD_16, CVT_V792_THRESHOLD_17, CVT_V792_THRESHOLD_18,
CVT_V792_THRESHOLD_19, CVT_V792_THRESHOLD_20, CVT_V792_THRESHOLD_21, CVT_V792_THRESHOLD_22,
CVT_V792_THRESHOLD_23, CVT_V792_THRESHOLD_24, CVT_V792_THRESHOLD_25, CVT_V792_THRESHOLD_26,
CVT_V792_THRESHOLD_27, CVT_V792_THRESHOLD_28, CVT_V792_THRESHOLD_29, CVT_V792_THRESHOLD_30,
CVT_V792_THRESHOLD_31
}
V792 discriminator threshold IDs.
enum CVT_V792_THRESHOLD_MSK { CVT_V792_THRESHOLD_VALUE_MSK = 0x00FF, CVT_V792_THRESHOLD_KILL_MSK = 0x0100 }
Threshold register bitmasks.
enum CVT_V792_BIT_SET_CLEAR_1_MSK { CVT_V792_BSC1_BERR_FLAG_MSK = 0x0008, CVT_V792_BSC1_SEL_ADDR_MSK = 0x0010, CVT_V792_BSC1_SOFT_RESET_MSK = 0x0080 }
V792 Bit Set\Clear 1 register masks.
enum CVT_V792_STATUS_1_MSK {
CVT_V792_STS1_DREADY_MSK = 0x0001, CVT_V792_STS1_GLOBAL_DREADY_MSK = 0x0002, CVT_V792_STS1_BUSY_MSK = 0x0004, CVT_V792_STS1_GLOBAL_BUSY_MSK = 0x0008,
CVT_V792_STS1_AMNESIA_MSK = 0x0010, CVT_V792_STS1_PURGED_MSK = 0x0020, CVT_V792_STS1_TERM_ON_MSK = 0x0040, CVT_V792_STS1_TERM_OFF_MSK = 0x0080,
CVT_V792_STS1_EVREADY_MSK = 0x0100
}
V792 Status 1 register bit masks.
enum CVT_V792_CONTROL_1_MSK { CVT_V792_CTRL1_BLKEND_MSK = 0x0004, CVT_V792_CTRL1_PROG_RESET_MSK = 0x0010, CVT_V792_CTRL1_BERR_ENABLE_MSK = 0x0020, CVT_V792_CTRL1_ALIGN64_MSK = 0x0040 }
V792 Control 1 register bit masks.
enum CVT_V792_MCST_CBLT_CTRL_MSK { CVT_V792_MCCTRL_DISABLED_BOARD_MSK = 0x0000, CVT_V792_MCCTRL_LAST_BOARD_MSK = 0x0001, CVT_V792_MCCTRL_FIRST_BOARD_MSK = 0x0002, CVT_V792_MCCTRL_MID_BOARD_MSK = 0x0003 }
V792 CVT_V792/MCST Control register bit masks.
enum CVT_V792_STATUS_2_MSK {
CVT_V792_STS2_BUFFER_EMPTY_MSK = 0x0002, CVT_V792_STS2_BUFFER_FULL_MSK = 0x0004, CVT_V792_STS2_DSEL_0_MSK = 0x0010, CVT_V792_STS2_DSEL_1_MSK = 0x0020,
CVT_V792_STS2_CSEL_0_MSK = 0x0040, CVT_V792_STS2_CSEL_1_MSK = 0x0080
}
V792 Status 2 register bit masks.
enum CVT_V792_BIT_SET_CLEAR_2_MSK {
CVT_V792_BSC2_TEST_MEM_MSK = 0x0001, CVT_V792_BSC2_OFFLINE_MSK = 0x0002, CVT_V792_BSC2_CLEAR_DATA_MSK = 0x0004, CVT_V792_BSC2_OVER_RANGE_DIS_MSK = 0x0008,
CVT_V792_BSC2_LOW_THR_DIS_MSK = 0x0010, CVT_V792_BSC2_TEST_ACQ_MSK = 0x0040, CVT_V792_BSC2_SLIDE_EN_MSK = 0x0080, CVT_V792_BSC2_STEP_TH_MSK = 0x0100,
CVT_V792_BSC2_AUTO_INC_MSK = 0x0800, CVT_V792_BSC2_EMPTY_EN_MSK = 0x1000, CVT_V792_BSC2_SLIDE_SUB_EN_MSK = 0x2000, CVT_V792_BSC2_ALL_TRG_MSK = 0x4000
}
V792 Bit Set\Clear 2 register masks.
Functions
CVT_DLL_API BOOL cvt_V792_open (cvt_V792_data *p_data, UINT16 base_address, long vme_handle, CVT_QTP_TYPES type)
V792 VME boards data initialization.
CVT_DLL_API BOOL cvt_V792_close (cvt_V792_data *p_data)
V792 VME boards closing and resource free.
CVT_DLL_API BOOL cvt_V792_set_geo_address (cvt_V792_data *p_data, UINT8 value)
Sets the geographical address.
CVT_DLL_API BOOL cvt_V792_get_geo_address (cvt_V792_data *p_data, UINT8 *p_value)
Gets the geographical address.
CVT_DLL_API BOOL cvt_V792_set_MCST_CBLT_address (cvt_V792_data *p_data, UINT8 value)
Sets the MCST\CBLT address.
CVT_DLL_API BOOL cvt_V792_get_MCST_CBLT_address (cvt_V792_data *p_data, UINT8 *p_value)
Gets the MCST\CBLT address.
CVT_DLL_API BOOL cvt_V792_set_bit_set_1 (cvt_V792_data *p_data, UINT16 value)
Set the bit set 1 register.
CVT_DLL_API BOOL cvt_V792_set_bit_clear_1 (cvt_V792_data *p_data, UINT16 value)
Set the bit clear 1 register.
CVT_DLL_API BOOL cvt_V792_set_interrupt_level (cvt_V792_data *p_data, UINT8 value)
Set the interrupt level register.
CVT_DLL_API BOOL cvt_V792_get_interrupt_level (cvt_V792_data *p_data, UINT8 *p_value)
Set the interrupt level register.
CVT_DLL_API BOOL cvt_V792_set_interrupt_vector (cvt_V792_data *p_data, UINT8 value)
Set the interrupt level register.
CVT_DLL_API BOOL cvt_V792_get_interrupt_vector (cvt_V792_data *p_data, UINT8 *p_value)
Get the interrupt vector register.
CVT_DLL_API BOOL cvt_V792_get_status_1 (cvt_V792_data *p_data, UINT16 *p_value)
Get the status 1 register.
CVT_DLL_API BOOL cvt_V792_set_control_1 (cvt_V792_data *p_data, UINT16 value)
Set to control 1 register.
CVT_DLL_API BOOL cvt_V792_get_control_1 (cvt_V792_data *p_data, UINT16 *p_value)
Get the control 1 register.
CVT_DLL_API BOOL cvt_V792_clear_bitmask_control_1 (cvt_V792_data *p_data, CVT_V792_CONTROL_1_MSK value)
Clear a bitmask to control 1 register.
CVT_DLL_API BOOL cvt_V792_set_bitmask_control_1 (cvt_V792_data *p_data, CVT_V792_CONTROL_1_MSK value)
Set a bitmask to control 1 register.
CVT_DLL_API BOOL cvt_V792_set_ader_high (cvt_V792_data *p_data, UINT8 value)
Set the address decoder high register.
CVT_DLL_API BOOL cvt_V792_get_ader_high (cvt_V792_data *p_data, UINT8 *p_value)
Get the address decoder high register.
CVT_DLL_API BOOL cvt_V792_get_ader_low (cvt_V792_data *p_data, UINT8 *p_value)
Get the address decoder high register.
CVT_DLL_API BOOL cvt_V792_single_shot_reset (cvt_V792_data *p_data)
Perfoms a single shot reset.
CVT_DLL_API BOOL cvt_V792_set_MCST_CBLT_control (cvt_V792_data *p_data, UINT8 value)
Set the MCST/CBLT Control register.
CVT_DLL_API BOOL cvt_V792_get_MCST_CBLT_control (cvt_V792_data *p_data, UINT8 *p_value)
Get the MCST/CBLT Control register.
CVT_DLL_API BOOL cvt_V792_set_event_trigger (cvt_V792_data *p_data, UINT8 value)
Set the Event trigger register.
CVT_DLL_API BOOL cvt_V792_get_event_trigger (cvt_V792_data *p_data, UINT8 *p_value)
Get the Event trigger register.
CVT_DLL_API BOOL cvt_V792_get_status_2 (cvt_V792_data *p_data, UINT16 *p_value)
Get the status 1 register.
CVT_DLL_API BOOL cvt_V792_set_threshold (cvt_V792_data *p_data, cvt_V792_threshold_id threshold_id, UINT16 value)
Set the specified threshold register.
CVT_DLL_API BOOL cvt_V792_set_dual_range_threshold (cvt_V792_data *p_data, cvt_V792_threshold_id threshold_id, UINT16 value_high, UINT16 value_low)
Set the specified threshold register for dual range board (V965 and V1785).
CVT_DLL_API BOOL cvt_V792_set_bit_set_2 (cvt_V792_data *p_data, UINT16 value)
Set the bit set 2 register.
CVT_DLL_API BOOL cvt_V792_set_bit_clear_2 (cvt_V792_data *p_data, UINT16 value)
Set the bit clear 2 register.
CVT_DLL_API BOOL cvt_V792_set_sliding_scale (cvt_V792_data *p_data, BOOL enable)
Setups the sliding scale feature.
CVT_DLL_API BOOL cvt_V792_set_zero_suppression (cvt_V792_data *p_data, BOOL enable, BOOL step_threshold, const UINT16 *thresholds_buff)
Setups the zero suppression feature.
CVT_DLL_API BOOL cvt_V792_set_dual_range_zero_suppression (cvt_V792_data *p_data, BOOL enable, BOOL step_threshold, const UINT16 *thresholds_buff_high, const UINT16 *thresholds_buff_low)
Setups the zero suppression feature for dual range boards (V965 or V1785).
CVT_DLL_API BOOL cvt_V792_set_overflow_suppression (cvt_V792_data *p_data, BOOL enable)
Setups the overflow suppression feature.
CVT_DLL_API BOOL cvt_V792_set_MEB (cvt_V792_data *p_data, BOOL empty_enable, BOOL auto_incr_enable)
Setups the Multiple Event Buffer.
CVT_DLL_API BOOL cvt_V792_set_event_counter (cvt_V792_data *p_data, BOOL count_all_events, BOOL reset_count)
Setups the event counter.
CVT_DLL_API BOOL cvt_V792_read_MEB (cvt_V792_data *p_data, void *p_buff, UINT32 *p_buff_size)
Reads data from Multiple event buffer and stores to user buffer.
CVT_DLL_API BOOL cvt_V792_set_fast_clear_window (cvt_V792_data *p_data, UINT16 value)
Set the fast clear window register.
CVT_DLL_API BOOL cvt_V792_set_acquisition_mode (cvt_V792_data *p_data, BOOL sliding_scale_enable, BOOL zero_suppression_enable, BOOL overflow_suppression_enable, BOOL empty_enable, BOOL count_all_events)
Setups the acquisition mode parameters.
CVT_DLL_API BOOL cvt_V792_set_interrupt (cvt_V792_data *p_data, UINT8 level, UINT8 vector, UINT8 event_number)
Setups interrupt parameters.
CVT_DLL_API BOOL cvt_V792_set_readout_mode (cvt_V792_data *p_data, BOOL bus_error_enable, BOOL block_end_enable, BOOL align64_enable)
Setups data readout mode parameters.
CVT_DLL_API BOOL cvt_V792_get_status (cvt_V792_data *p_data, BOOL *p_is_data_ready, BOOL *p_is_busy, BOOL *p_is_term_on, BOOL *p_is_buffer_full)
Gets information about board status.
CVT_DLL_API BOOL cvt_V792_set_crate_number (cvt_V792_data *p_data, UINT8 crate_number)
Setups the crate number.
CVT_DLL_API BOOL cvt_V792_set_pedestal (cvt_V792_data *p_data, UINT8 value)
Set the pedestal value.
CVT_DLL_API BOOL cvt_V792_get_event_counter (cvt_V792_data *p_data, UINT32 *p_counter)
Gets the event counter value.
CVT_DLL_API BOOL cvt_V792_get_system_info (cvt_V792_data *p_data, UINT16 *p_firmware_rev, UINT8 *p_piggy_back_type, UINT16 *p_serial_number)
Gets board's system information.
CVT_DLL_API const char * cvt_V792_get_piggy_back_str (cvt_V792_data *p_data, UINT8 piggy_back_type)
Returns ths mounted piggy back type string.
CVT_DLL_API BOOL cvt_V792_software_reset (cvt_V792_data *p_data)
Performs a software reset.
CVT_DLL_API BOOL cvt_V792_data_clear (cvt_V792_data *p_data)
Performs a data clear.
CVT_DLL_API BOOL cvt_V792_read_data (cvt_V792_data *p_data)
Reads new data from MEB and stores into internal queue.
CVT_DLL_API BOOL cvt_V792_peek_event (cvt_V792_data *p_data, UINT32 *out_buff, long *p_out_buff_size, UINT32 *p_event_count, BOOL dequeue)
Tries to peek (i.e. copy but not removing) an event from queue and save data to output buffer.
CVT_DLL_API BOOL cvt_V792_peek_channel_data (cvt_V792_data *p_data, UINT8 channel_index, UINT16 *out_buff, long *p_out_buff_size, UINT32 *p_event_count, BOOL dequeue)
Tries to peek (i.e. copy but not removing) an event from queue and save ADC data for the specific channel to output buffer.
CVT_DLL_API BOOL cvt_V792_inqueue (cvt_V792_data *p_data, const UINT32 *in_buff, UINT32 in_buff_size)
Tries to put in_buff_size data word to queue.
CVT_DLL_API BOOL cvt_V792_dequeue (cvt_V792_data *p_data, UINT32 *out_buff, UINT32 out_buff_size)
Tries to get out_buff_size data word from the queue.
CVT_DLL_API long cvt_V792_get_queue_free (cvt_V792_data *p_data)
Gets the number of free queue space (words).
CVT_DLL_API long cvt_V792_get_queue_length (cvt_V792_data *p_data)
Gets the queue length.
CVT_DLL_API BOOL cvt_V792_set_MCST_CBLT (cvt_V792_data *p_data, UINT8 address, MCST_CBLT_board_pos pos)
Setups MCST/CBLT parameters this board.
CVT_DLL_API const char * cvt_V792_SW_rev (void)
Returns the SDK software release.
Variables
const int CVT_QTP_NUM_CHANNELS []
The number of channels foreach specific board.
Detailed Description
V792 VME board definitions.
Author:
NDA
Version:
1.0
Date:
03/2006
Provides methods, properties and defines to handle V792 VME boards
Definition in file cvt_V792.h.
Define Documentation
#define CVT_V792_QUEUE_SIZE_DWORD (1024*1024)
V792 data queue size.
This is the number of UINT32 words storage into the V792 builtin data queue
Definition at line 43 of file cvt_V792.h.
Referenced by cvt_V792_dequeue(), cvt_V792_get_queue_free(), cvt_V792_get_queue_length(), cvt_V792_inqueue(), cvt_V792_open(), cvt_V792_peek_channel_data(), and cvt_V792_peek_event().
#define CVT_V792_STS2_PIGGY_BACK_TYPE_MSK 0x00F0
CVT_V792_STATUS_2 register piggy-back type bitmasks.
Definition at line 506 of file cvt_V792.h.
#define CVT_V792_USE_DATA_QUEUE 1
Enable/ disable V792 builtin data queue.
Define this to enable V792 builtin data queue; comment out to disable this feature
Definition at line 33 of file cvt_V792.h.
Enumeration Type Documentation
enum CVT_QTP_TYPES
The QTP board type.
Provides an entry foreach supported board type
Enumerator:
CVT_V792_TYPE_A The board is V792A.
CVT_V792_TYPE_N The board is V792N.
CVT_V862_TYPE_A The board is V862A.
CVT_V965 The board is V965.
CVT_V965_TYPE_A The board is V965A.
CVT_V785_TYPE_A The board is V785A.
CVT_V785_TYPE_N The board is V785N.
CVT_V1785 The board is V1785.
CVT_V775_TYPE_A The board is V775A.
CVT_V775_TYPE_N The board is V775N.
Definition at line 53 of file cvt_V792.h.
enum CVT_V792_BIT_SET_CLEAR_1_MSK
V792 Bit Set\Clear 1 register masks.
Enumerator:
CVT_V792_BSC1_BERR_FLAG_MSK Bus Error Flag bit
CVT_V792_BSC1_SEL_ADDR_MSK Select Address bit.
CVT_V792_BSC1_SOFT_RESET_MSK Software RESET bit.
Definition at line 433 of file cvt_V792.h.
enum CVT_V792_BIT_SET_CLEAR_2_MSK
V792 Bit Set\Clear 2 register masks.
Enumerator:
CVT_V792_BSC2_TEST_MEM_MSK Random Memory Access Test Mode bit
CVT_V792_BSC2_OFFLINE_MSK Offline bit.
CVT_V792_BSC2_CLEAR_DATA_MSK Clear Data bit.
CVT_V792_BSC2_OVER_RANGE_DIS_MSK Overflow suppression disable bit.
CVT_V792_BSC2_LOW_THR_DIS_MSK Zero suppression disable bit.
CVT_V792_BSC2_TEST_ACQ_MSK Acquisition Test Mode bit.
CVT_V792_BSC2_SLIDE_EN_MSK Sliding scale enale/disable bit.
CVT_V792_BSC2_STEP_TH_MSK Zero suppression threshold resolution bit.
CVT_V792_BSC2_AUTO_INC_MSK enable/disable the automatic increment of the readout pointer bit.
CVT_V792_BSC2_EMPTY_EN_MSK Choose if writing the header and EOB when there are no accepted channels.
CVT_V792_BSC2_SLIDE_SUB_EN_MSK Change operation mode for the sliding scale bit.
CVT_V792_BSC2_ALL_TRG_MSK Choose how to increment the event counter.
Definition at line 515 of file cvt_V792.h.
enum CVT_V792_CONTROL_1_MSK
V792 Control 1 register bit masks.
Enumerator:
CVT_V792_CTRL1_BLKEND_MSK End of Block bit
CVT_V792_CTRL1_PROG_RESET_MSK Programmable reset mode bit
CVT_V792_CTRL1_BERR_ENABLE_MSK Bus error enable bit
CVT_V792_CTRL1_ALIGN64_MSK Align 64 bit
Definition at line 468 of file cvt_V792.h.
enum CVT_V792_MCST_CBLT_CTRL_MSK
V792 CVT_V792/MCST Control register bit masks.
Enumerator:
CVT_V792_MCCTRL_DISABLED_BOARD_MSK Disabled Board mask
CVT_V792_MCCTRL_LAST_BOARD_MSK Last Board mask
CVT_V792_MCCTRL_FIRST_BOARD_MSK First Board mask
CVT_V792_MCCTRL_MID_BOARD_MSK Middle Board mask
Definition at line 482 of file cvt_V792.h.
enum CVT_V792_REG_INDEX
The registers indexes.
Provides an entry for each register: This is the index into the CVT_V792_REG_TABLE board table
Enumerator:
CVT_V792_OUT_BUFFER_INDEX Output buffer index.
CVT_V792_FW_REV_INDEX Firmware Revision register index.
CVT_V792_GEO_ADDRESS_INDEX Geo Address register index.
CVT_V792_MCST_CBLT_ADDRESS_INDEX MCST/CBLT Address register index.
CVT_V792_BIT_SET_1_INDEX Bit Set 1 register index.
CVT_V792_BIT_CLEAR_1_INDEX Bit Clear 1 register index.
CVT_V792_INT_LEVEL_INDEX Interrupt level register index.
CVT_V792_INT_VECTOR_INDEX Interrupt vector register index.
CVT_V792_STATUS_1_INDEX Status 1 register index.
CVT_V792_CONTROL_1_INDEX Control 1 register index.
CVT_V792_ADER_HIGH_INDEX Address decoder HIGH register index.
CVT_V792_ADER_LOW_INDEX Address decoder LOW register index.
CVT_V792_SINGLE_SHOT_RESET_INDEX Single Shot Reset register index.
CVT_V792_MCST_CBLT_CTRL_INDEX MCST/CBLT control register index.
CVT_V792_EVENT_TRG_INDEX Event trigger register index.
CVT_V792_STATUS_2_INDEX Status 2 register index.
CVT_V792_EVENT_COUNTER_LOW_INDEX Event counter low register index.
CVT_V792_EVENT_COUNTER_HIGH_INDEX Event counter high register index.
CVT_V792_INC_EVENT_INDEX Increment Event register index.
CVT_V792_INC_OFFSET_INDEX Increment Offset register index.
CVT_V792_LOAD_TEST_INDEX Load Test register index.
CVT_V792_FCLR_WND_INDEX FCLR window register index.
CVT_V792_BIT_SET_2_INDEX Bit Set 2 register index.
CVT_V792_BIT_CLEAR_2_INDEX Bit Clear 2 register index.
CVT_V792_W_MEMORY_TEST_ADDRESS_INDEX W Memory Test Address register index.
CVT_V792_MEMORY_TEST_WORD_HIGH_INDEX Memory Test Word High register index.
CVT_V792_MEMORY_TEST_WORD_LOW_INDEX Memory Test Word Low register index.
CVT_V792_CRATE_SELECT_INDEX Crate select register index.
CVT_V792_TEST_EVENT_WRITE_INDEX Test Event register Write index.
CVT_V792_EVENT_COUNT_RESET_INDEX Event Counter Reset register index.
CVT_V792_IPED_INDEX Iped register index.
CVT_V792_R_TEST_ADDRESS_INDEX R Test Address register index.
CVT_V792_SW_COMM_INDEX SW Comm register index.
CVT_V792_SLIDE_CONSTANT_INDEX Sliding constant register index.
CVT_V792_AAD_INDEX AAD register index.
CVT_V792_BAD_INDEX BAD register index.
CVT_V792_THRESHOLD_0_INDEX Threshold 0 register index (Ch 0 -> V792A Ch 0 -> V792N).
CVT_V792_THRESHOLD_1_INDEX Threshold 1 register index (Ch 1 -> V792A).
CVT_V792_THRESHOLD_2_INDEX Threshold 2 register index (Ch 2 -> V792A Ch 1 -> V792N).
CVT_V792_THRESHOLD_3_INDEX Threshold 3 register index (Ch 3 -> V792A).
CVT_V792_THRESHOLD_4_INDEX Threshold 4 register index (Ch 4 -> V792A Ch 2 -> V792N).
CVT_V792_THRESHOLD_5_INDEX Threshold 5 register index (Ch 5 -> V792A).
CVT_V792_THRESHOLD_6_INDEX Threshold 6 register index (Ch 6 -> V792A Ch 3 -> V792N).
CVT_V792_THRESHOLD_7_INDEX Threshold 7 register index (Ch 7 -> V792A).
CVT_V792_THRESHOLD_8_INDEX Threshold 8 register index (Ch 8 -> V792A Ch 4 -> V792N).
CVT_V792_THRESHOLD_9_INDEX Threshold 9 register index (Ch 9 -> V792A).
CVT_V792_THRESHOLD_10_INDEX Threshold 10 register index (Ch 10 -> V792A Ch 5 -> V792N).
CVT_V792_THRESHOLD_11_INDEX Threshold 11 register index (Ch 11 -> V792A).
CVT_V792_THRESHOLD_12_INDEX Threshold 12 register index (Ch 12 -> V792A Ch 6 -> V792N).
CVT_V792_THRESHOLD_13_INDEX Threshold 13 register index (Ch 13 -> V792A).
CVT_V792_THRESHOLD_14_INDEX Threshold 14 register index (Ch 14 -> V792A Ch 7 -> V792N).
CVT_V792_THRESHOLD_15_INDEX Threshold 15 register index (Ch 15 -> V792A).
CVT_V792_THRESHOLD_16_INDEX Threshold 16 register index (Ch 16 -> V792A Ch 8 -> V792N).
CVT_V792_THRESHOLD_17_INDEX Threshold 17 register index (Ch 17 -> V792A).
CVT_V792_THRESHOLD_18_INDEX Threshold 18 register index (Ch 18 -> V792A Ch 9 -> V792N).
CVT_V792_THRESHOLD_19_INDEX Threshold 19 register index (Ch 19 -> V792A).
CVT_V792_THRESHOLD_20_INDEX Threshold 20 register index (Ch 20 -> V792A Ch 10 -> V792N).
CVT_V792_THRESHOLD_21_INDEX Threshold 21 register index (Ch 21 -> V792A).
CVT_V792_THRESHOLD_22_INDEX Threshold 22 register index (Ch 22 -> V792A Ch 11 -> V792N).
CVT_V792_THRESHOLD_23_INDEX Threshold 23 register index (Ch 23 -> V792A).
CVT_V792_THRESHOLD_24_INDEX Threshold 24 register index (Ch 24 -> V792A Ch 12 -> V792N).
CVT_V792_THRESHOLD_25_INDEX Threshold 25 register index (Ch 25 -> V792A).
CVT_V792_THRESHOLD_26_INDEX Threshold 26 register index (Ch 26 -> V792A Ch 13 -> V792N).
CVT_V792_THRESHOLD_27_INDEX Threshold 27 register index (Ch 27 -> V792A).
CVT_V792_THRESHOLD_28_INDEX Threshold 28 register index (Ch 28 -> V792A Ch 14 -> V792N).
CVT_V792_THRESHOLD_29_INDEX Threshold 29 register index (Ch 29 -> V792A).
CVT_V792_THRESHOLD_30_INDEX Threshold 30 register index (Ch 30 -> V792A Ch 15 -> V792N).
CVT_V792_THRESHOLD_31_INDEX Threshold 31 register index (Ch 31 -> V792A).
CVT_V792_ROM_OUI_2_INDEX Manufacturer identifier (IEEE OUI) (MSB) index.
CVT_V792_ROM_OUI_1_INDEX Manufacturer identifier (IEEE OUI) index.
CVT_V792_ROM_OUI_0_INDEX Manufacturer identifier (IEEE OUI) (LSB) index.
CVT_V792_ROM_VERSION_INDEX Purchased version of the Mod.V792 index.
CVT_V792_ROM_BOARD_ID_2_INDEX Board identifier (MSB) index.
CVT_V792_ROM_BOARD_ID_1_INDEX Board identifier index.
CVT_V792_ROM_BOARD_ID_0_INDEX Board identifier (LSB) index.
CVT_V792_ROM_REVISION_INDEX Hardware revision identifier index.
CVT_V792_ROM_SERIAL_1_INDEX Serial number (MSB) index.
CVT_V792_ROM_SERIAL_0_INDEX Serial number (LSB) index.
Definition at line 285 of file cvt_V792.h.
enum CVT_V792_STATUS_1_MSK
V792 Status 1 register bit masks.
Enumerator:
CVT_V792_STS1_DREADY_MSK Data Ready
CVT_V792_STS1_GLOBAL_DREADY_MSK At least one module has Data Ready.
CVT_V792_STS1_BUSY_MSK Module Busy.
CVT_V792_STS1_GLOBAL_BUSY_MSK At least one module is Busy.
CVT_V792_STS1_AMNESIA_MSK GEO is not available from the JAUX.
CVT_V792_STS1_PURGED_MSK The board is purged.
CVT_V792_STS1_TERM_ON_MSK All Control Bus Terminations are ON.
CVT_V792_STS1_TERM_OFF_MSK All Control Bus Terminations are OFF.
CVT_V792_STS1_EVREADY_MSK Indicates that the number in the Event Trigger Register is greater than or equal to the number of events stored in the memory and an interrupt request has been generated with interrupt level different from 0
Definition at line 446 of file cvt_V792.h.
enum CVT_V792_STATUS_2_MSK
V792 Status 2 register bit masks.
Enumerator:
CVT_V792_STS2_BUFFER_EMPTY_MSK Buffer empty.
CVT_V792_STS2_BUFFER_FULL_MSK Buffer full.
CVT_V792_STS2_DSEL_0_MSK Indicate the type of piggy-back plugged into the board (bit 0).
CVT_V792_STS2_DSEL_1_MSK Indicate the type of piggy-back plugged into the board (bit 1).
CVT_V792_STS2_CSEL_0_MSK Indicate the type of piggy-back plugged into the board (bit 2).
CVT_V792_STS2_CSEL_1_MSK Indicate the type of piggy-back plugged into the board (bit 3).
Definition at line 496 of file cvt_V792.h.
enum cvt_V792_threshold_id
V792 discriminator threshold IDs.
Enumerator:
CVT_V792_THRESHOLD_ALL Catch all the thresholds
CVT_V792_THRESHOLD_0 Threshold 0 register
CVT_V792_THRESHOLD_1 Threshold 1 register
CVT_V792_THRESHOLD_2 Threshold 2 register
CVT_V792_THRESHOLD_3 Threshold 3 register
CVT_V792_THRESHOLD_4 Threshold 4 register
CVT_V792_THRESHOLD_5 Threshold 5 register
CVT_V792_THRESHOLD_6 Threshold 6 register
CVT_V792_THRESHOLD_7 Threshold 7 register
CVT_V792_THRESHOLD_8 Threshold 8 register
CVT_V792_THRESHOLD_9 Threshold 9 register
CVT_V792_THRESHOLD_10 Threshold 10 register
CVT_V792_THRESHOLD_11 Threshold 11 register
CVT_V792_THRESHOLD_12 Threshold 12 register
CVT_V792_THRESHOLD_13 Threshold 13 register
CVT_V792_THRESHOLD_14 Threshold 14 register
CVT_V792_THRESHOLD_15 Threshold 15 register
CVT_V792_THRESHOLD_16 Threshold 16 register
CVT_V792_THRESHOLD_17 Threshold 17 register
CVT_V792_THRESHOLD_18 Threshold 18 register
CVT_V792_THRESHOLD_19 Threshold 19 register
CVT_V792_THRESHOLD_20 Threshold 20 register
CVT_V792_THRESHOLD_21 Threshold 21 register
CVT_V792_THRESHOLD_22 Threshold 22 register
CVT_V792_THRESHOLD_23 Threshold 23 register
CVT_V792_THRESHOLD_24 Threshold 24 register
CVT_V792_THRESHOLD_25 Threshold 25 register
CVT_V792_THRESHOLD_26 Threshold 26 register
CVT_V792_THRESHOLD_27 Threshold 27 register
CVT_V792_THRESHOLD_28 Threshold 28 register
CVT_V792_THRESHOLD_29 Threshold 29 register
CVT_V792_THRESHOLD_30 Threshold 30 register
CVT_V792_THRESHOLD_31 Threshold 31 register
Definition at line 372 of file cvt_V792.h.
enum CVT_V792_THRESHOLD_MSK
Threshold register bitmasks.
Enumerator:
CVT_V792_THRESHOLD_VALUE_MSK Threshold data bitmask
CVT_V792_THRESHOLD_KILL_MSK Threshold KILL bitmask
Definition at line 421 of file cvt_V792.h.
Function Documentation
CVT_DLL_API BOOL cvt_V792_clear_bitmask_control_1 (cvt_V792_data * p_data, CVT_V792_CONTROL_1_MSK value)
Clear a bitmask to control 1 register.
Clears the bits of the bitmask into the register. The inverted bitmask is ANDed to the actual regiter content
Parameters:
p_data Pointer to board data
value The bitmask to clear: may be a combination of CVT_V792_CONTROL_1_MSK bitmask
Returns:
TRUE: Procedure successfully executed
See also:
CVT_V792_CONTROL_1_MSK
Definition at line 442 of file cvt_V792.c.
References cvt_clear_bitmask(), CVT_V792_CONTROL_1_ADD, CVT_V792_CONTROL_1_AM, CVT_V792_CONTROL_1_DATA_SIZE, FALSE, cvt_V792_data::m_common_data, TRACE, and TRUE.
CVT_DLL_API BOOL cvt_V792_close (cvt_V792_data * p_data)
V792 VME boards closing and resource free.
Provides specific handling for V792 boards closing.
Parameters:
p_data Pointer to board data
Returns:
TRUE: board successfully closed
Note:
Must be called when done with any other board specific API.
Definition at line 197 of file cvt_V792.c.
References cvt_board_close(), FALSE, cvt_V792_data::m_common_data, cvt_V792_data::m_queue, and TRUE.
CVT_DLL_API BOOL cvt_V792_data_clear (cvt_V792_data * p_data)
Performs a data clear.
Pulses the CVT_V792_BSC2_CLEAR_DATA_MSK bit and clears the event counter.
Parameters:
p_data Pointer to board data
Returns:
TRUE: Procedure successfully executed
See also:
CVT_V792_BSC2_CLEAR_DATA_MSK
Definition at line 1533 of file cvt_V792.c.
References CVT_V792_BIT_CLEAR_2_INDEX, CVT_V792_BIT_SET_2_INDEX, CVT_V792_BSC2_CLEAR_DATA_MSK, CVT_V792_EVENT_COUNT_RESET_INDEX, cvt_write_reg(), FALSE, cvt_V792_data::m_common_data, TRACE, and TRUE.
CVT_DLL_API BOOL cvt_V792_dequeue (cvt_V792_data * p_data, UINT32 * out_buff, UINT32 out_buff_size)
Tries to get out_buff_size data word from the queue.
Checks for queue available data words and gets data beginning from m_queue_ini. m_queue_ini will be update: if out_buff!= NULL the data will be stored into it.
Parameters:
p_data Pointer to board data
out_buff Pointer to output buffer (may be NULL)
out_buff_size Size of out_buff (UINT32)
Returns:
TRUE: data removed correctly, FALSE elsewhere (e.g. queue underflow)
Definition at line 1895 of file cvt_V792.c.
References cvt_V792_get_queue_length(), CVT_V792_QUEUE_SIZE_DWORD, FALSE, cvt_V792_data::m_queue, cvt_V792_data::m_queue_ini, and TRUE.
Referenced by cvt_V792_peek_channel_data(), and cvt_V792_peek_event().
CVT_DLL_API BOOL cvt_V792_get_ader_high (cvt_V792_data * p_data, UINT8 * p_value)
Get the address decoder high register.
Reads the address decoder high register.
Parameters:
p_data Pointer to board data
p_value The value read
Returns:
TRUE: Procedure successfully executed
Definition at line 472 of file cvt_V792.c.
References cvt_read_reg(), CVT_V792_ADER_HIGH_INDEX, FALSE, cvt_V792_data::m_common_data, TRACE, and TRUE.
CVT_DLL_API BOOL cvt_V792_get_ader_low (cvt_V792_data * p_data, UINT8 * p_value)
Get the address decoder high register.
Reads the address decoder low register.
Parameters:
p_data Pointer to board data
p_value The value read
Returns:
TRUE: Procedure successfully executed
Definition at line 503 of file cvt_V792.c.
References cvt_read_reg(), CVT_V792_ADER_LOW_INDEX, FALSE, cvt_V792_data::m_common_data, TRACE, and TRUE.
CVT_DLL_API BOOL cvt_V792_get_control_1 (cvt_V792_data * p_data, UINT16 * p_value)
Get the control 1 register.
Reads the control 1 register.
Parameters:
p_data Pointer to board data
p_value The value read
Returns:
TRUE: Procedure successfully executed
Definition at line 411 of file cvt_V792.c.
References cvt_read_reg(), CVT_V792_CONTROL_1_INDEX, FALSE, cvt_V792_data::m_common_data, TRACE, and TRUE.
CVT_DLL_API BOOL cvt_V792_get_event_counter (cvt_V792_data * p_data, UINT32 * p_counter)
Gets the event counter value.
Gets the event counter actual value.
Parameters:
p_data Pointer to board data
p_counter Pointer to the counter value.
Returns:
TRUE: Procedure successfully executed
Definition at line 1417 of file cvt_V792.c.
References cvt_read_reg(), CVT_V792_EVENT_COUNTER_HIGH_INDEX, CVT_V792_EVENT_COUNTER_LOW_INDEX, FALSE, cvt_V792_data::m_common_data, TRACE, and TRUE.
CVT_DLL_API BOOL cvt_V792_get_event_trigger (cvt_V792_data * p_data, UINT8 * p_value)
Get the Event trigger register.
Reads the event trigger register.
Parameters:
p_data Pointer to board data
p_value The value read
Returns:
TRUE: Procedure successfully executed
Definition at line 580 of file cvt_V792.c.
References cvt_read_reg(), CVT_V792_EVENT_TRG_INDEX, FALSE, cvt_V792_data::m_common_data, TRACE, and TRUE.
CVT_DLL_API BOOL cvt_V792_get_geo_address (cvt_V792_data * p_data, UINT8 * p_value)
Gets the geographical address.
Reads the geographical address register.
Parameters:
p_data Pointer to board data
p_value The value read
Returns:
TRUE: Procedure successfully executed
Definition at line 241 of file cvt_V792.c.
References cvt_read_reg(), CVT_V792_GEO_ADDRESS_INDEX, FALSE, cvt_V792_data::m_common_data, TRACE, and TRUE.
CVT_DLL_API BOOL cvt_V792_get_interrupt_level (cvt_V792_data * p_data, UINT8 * p_value)
Set the interrupt level register.
Reads the interrupt level register.
Parameters:
p_data Pointer to board data
p_value The value read
Returns:
TRUE: Procedure successfully executed
Definition at line 333 of file cvt_V792.c.
References cvt_read_reg(), CVT_V792_INT_LEVEL_INDEX, FALSE, cvt_V792_data::m_common_data, TRACE, and TRUE.
CVT_DLL_API BOOL cvt_V792_get_interrupt_vector (cvt_V792_data * p_data, UINT8 * p_value)
Get the interrupt vector register.
Reads the interrupt vector register.
Parameters:
p_data Pointer to board data
p_value The value read
Returns:
TRUE: Procedure successfully executed
Definition at line 364 of file cvt_V792.c.
References cvt_read_reg(), CVT_V792_INT_VECTOR_INDEX, FALSE, cvt_V792_data::m_common_data, TRACE, and TRUE.
CVT_DLL_API BOOL cvt_V792_get_MCST_CBLT_address (cvt_V792_data * p_data, UINT8 * p_value)
Gets the MCST\CBLT address.
Reads the MCST\CBLT address register. This register contains the most significant bits of the MCST/CBLT address of the module set via VME.
Parameters:
p_data Pointer to board data
p_value The value read
Returns:
TRUE: Procedure successfully executed
Definition at line 272 of file cvt_V792.c.
References cvt_read_reg(), CVT_V792_MCST_CBLT_ADDRESS_INDEX, FALSE, cvt_V792_data::m_common_data, TRACE, and TRUE.
CVT_DLL_API BOOL cvt_V792_get_MCST_CBLT_control (cvt_V792_data * p_data, UINT8 * p_value)
Get the MCST/CBLT Control register.
Reads the MCST/CBLT Control register.
Parameters:
p_data Pointer to board data
p_value The value read
Returns:
TRUE: Procedure successfully executed
Definition at line 549 of file cvt_V792.c.
References cvt_read_reg(), CVT_V792_MCST_CBLT_CTRL_INDEX, FALSE, cvt_V792_data::m_common_data, TRACE, and TRUE.
CVT_DLL_API const char* cvt_V792_get_piggy_back_str (cvt_V792_data * p_data, UINT8 piggy_back_type)
Returns ths mounted piggy back type string.
Parameters:
p_data Pointer to board data
piggy_back_type The piggy back type numerical value (as returned from BOOL cvt_V792_get_system_info(cvt_V792_data* p_data, UINT16 *p_firmware_rev, UINT8 *p_piggy_back_type, UINT16 *p_serial_number).
Returns:
A user friendly string describing the piggy back type
Definition at line 1483 of file cvt_V792.c.
CVT_DLL_API long cvt_V792_get_queue_free (cvt_V792_data * p_data)
Gets the number of free queue space (words).
Parameters:
p_data Pointer to board data
Returns:
The number of free queue space (UINT32 words)
Definition at line 1929 of file cvt_V792.c.
References CVT_V792_QUEUE_SIZE_DWORD, cvt_V792_data::m_queue_end, and cvt_V792_data::m_queue_ini.
Referenced by cvt_V792_inqueue(), and cvt_V792_read_data().
CVT_DLL_API long cvt_V792_get_queue_length (cvt_V792_data * p_data)
Gets the queue length.
Parameters:
p_data Pointer to board data
Returns:
The queue length (UINT32 words)
Definition at line 1937 of file cvt_V792.c.
References CVT_V792_QUEUE_SIZE_DWORD, cvt_V792_data::m_queue_end, and cvt_V792_data::m_queue_ini.
Referenced by cvt_V792_dequeue().
CVT_DLL_API BOOL cvt_V792_get_status (cvt_V792_data * p_data, BOOL * p_is_data_ready, BOOL * p_is_busy, BOOL * p_is_term_on, BOOL * p_is_buffer_full)
Gets information about board status.
Parameters:
p_data Pointer to board data
p_is_data_ready Returns TRUE if data is ready.
p_is_busy Returns TRUE if board is busy.
p_is_term_on Returns TRUE if term bit is on.
p_is_buffer_full Returns TRUE if buffer is full.
Returns:
TRUE: Procedure successfully executed
Definition at line 1354 of file cvt_V792.c.
References cvt_read_reg(), CVT_V792_STATUS_1_INDEX, CVT_V792_STATUS_2_INDEX, CVT_V792_STS1_BUSY_MSK, CVT_V792_STS1_DREADY_MSK, CVT_V792_STS1_TERM_ON_MSK, CVT_V792_STS2_BUFFER_FULL_MSK, FALSE, cvt_V792_data::m_common_data, TRACE, and TRUE.
CVT_DLL_API BOOL cvt_V792_get_status_1 (cvt_V792_data * p_data, UINT16 * p_value)
Get the status 1 register.
Reads the status 1 register.
Parameters:
p_data Pointer to board data
p_value The value read
Returns:
TRUE: Procedure successfully executed
Definition at line 380 of file cvt_V792.c.
References cvt_read_reg(), CVT_V792_STATUS_1_INDEX, FALSE, cvt_V792_data::m_common_data, TRACE, and TRUE.
CVT_DLL_API BOOL cvt_V792_get_status_2 (cvt_V792_data * p_data, UINT16 * p_value)
Get the status 1 register.
Reads the status 2 register.
Parameters:
p_data Pointer to board data
p_value The value read
Returns:
TRUE: Procedure successfully executed
Definition at line 596 of file cvt_V792.c.
References cvt_read_reg(), CVT_V792_STATUS_2_INDEX, FALSE, cvt_V792_data::m_common_data, TRACE, and TRUE.
CVT_DLL_API BOOL cvt_V792_get_system_info (cvt_V792_data * p_data, UINT16 * p_firmware_rev, UINT8 * p_piggy_back_type, UINT16 * p_serial_number)
Gets board's system information.
Reads the firmware revision register, the board type and the serial number.
Parameters:
p_data Pointer to board data
p_firmware_rev The firmare release (MSB major release, LSB minor release).
p_piggy_back_type The mounted piggy back type.
p_serial_number The serial number.
Returns:
TRUE: Procedure successfully executed
Definition at line 1442 of file cvt_V792.c.
References cvt_read_reg(), CVT_V792_FW_REV_INDEX, CVT_V792_GET_PIGGY_BACK_TYPE, CVT_V792_ROM_SERIAL_0_INDEX, CVT_V792_ROM_SERIAL_1_INDEX, CVT_V792_STATUS_2_INDEX, FALSE, cvt_V792_data::m_common_data, TRACE, and TRUE.
CVT_DLL_API BOOL cvt_V792_inqueue (cvt_V792_data * p_data, const UINT32 * in_buff, UINT32 in_buff_size)
Tries to put in_buff_size data word to queue.
Checks for the queue available free words and stores data beginning from m_queue_end. m_queue_end will be update
Parameters:
p_data Pointer to board data
in_buff Pointer to input buffer
in_buff_size Size of in_buff (UINT32)
Returns:
TRUE: data stored correctly FALSE elsewhere (e.g. queue overflow)
Definition at line 1867 of file cvt_V792.c.
References cvt_V792_get_queue_free(), CVT_V792_QUEUE_SIZE_DWORD, FALSE, cvt_V792_data::m_queue, cvt_V792_data::m_queue_end, and TRUE.
Referenced by cvt_V792_read_data().
CVT_DLL_API BOOL cvt_V792_open (cvt_V792_data * p_data, UINT16 base_address, long vme_handle, CVT_QTP_TYPES type)
V792 VME boards data initialization.
Provides specific handling for V792 boards opening.
Parameters:
p_data Pointer to board data
base_address The board base address (MSW)
vme_handle The VME handle
type The board type : it must be a CVT_QTP_TYPES value
Returns:
TRUE: board successfully opened
Note:
Must be called before any other board specific API.
See also:
CVT_QTP_TYPES
< The board is V792A
< The board is V792N
< The board is V862A
< The board is V965
< The board is V965A
< The board is V785A
< The board is V785N
< The board is V1785
< The board is V775A
< The board is V775N
Definition at line 150 of file cvt_V792.c.
References cvt_board_open(), CVT_V1785, CVT_V775_TYPE_A, CVT_V775_TYPE_N, CVT_V785_TYPE_A, CVT_V785_TYPE_N, CVT_V792_QUEUE_SIZE_DWORD, cvt_V792_set_MCST_CBLT(), CVT_V792_TYPE_A, CVT_V792_TYPE_N, CVT_V862_TYPE_A, CVT_V965, CVT_V965_TYPE_A, FALSE, cvt_V792_data::m_common_data, cvt_V792_data::m_queue, cvt_V792_data::m_type, cvt_board_data::set_MCST_CBLT, TRACE, TRACE1, and TRUE.
CVT_DLL_API BOOL cvt_V792_peek_channel_data (cvt_V792_data * p_data, UINT8 channel_index, UINT16 * out_buff, long * p_out_buff_size, UINT32 * p_event_count, BOOL dequeue)
Tries to peek (i.e. copy but not removing) an event from queue and save ADC data for the specific channel to output buffer.
Scans the queue beginning from m_queue_ini, searching for an event block, and stores data output stream.
Parameters:
p_data Pointer to board data
channel_index The channel to get data from
out_buff Pointer to output buffer
p_out_buff_size Size of out_buff (UINT32). The number of data written into out_buff (UINT32) on exit.
p_event_count Requested event count. The found event count, on exit
dequeue If TRUE removes the found events from queue. !!! WARNING !!! the whole event will be deleted (i.e. other channels' data will be lost too)
Returns:
TRUE: some event found, FALSE elsewhere
Definition at line 1695 of file cvt_V792.c.
References CVT_QTP_DATA_TYPE_MSK, CVT_QTP_DATUM, CVT_QTP_GET_EOB_EVENT_COUNT, CVT_QTP_IS_EOB, CVT_QTP_IS_HEADER, CVT_V1785, CVT_V1785_GET_DATUM_ADC, CVT_V1785_GET_DATUM_CH, CVT_V1785_GET_DATUM_GEO, CVT_V1785_GET_DATUM_OV, CVT_V1785_GET_DATUM_UN, CVT_V775_GET_DATUM_ADC, CVT_V775_GET_DATUM_GEO, CVT_V775_GET_DATUM_OV, CVT_V775_GET_DATUM_UN, CVT_V775_TYPE_A, CVT_V775_TYPE_N, CVT_V775A_GET_DATUM_CH, CVT_V775N_GET_DATUM_CH, CVT_V785_GET_DATUM_ADC, CVT_V785_GET_DATUM_GEO, CVT_V785_GET_DATUM_OV, CVT_V785_GET_DATUM_UN, CVT_V785_TYPE_A, CVT_V785_TYPE_N, CVT_V785A_GET_DATUM_CH, CVT_V785N_GET_DATUM_CH, cvt_V792_dequeue(), CVT_V792_GET_DATUM_ADC, CVT_V792_GET_DATUM_GEO, CVT_V792_GET_DATUM_OV, CVT_V792_GET_DATUM_UN, CVT_V792_QUEUE_SIZE_DWORD, CVT_V792_TYPE_A, CVT_V792_TYPE_N, CVT_V792A_GET_DATUM_CH, CVT_V792N_GET_DATUM_CH, CVT_V965, CVT_V965_GET_DATUM_ADC, CVT_V965_GET_DATUM_CH, CVT_V965_GET_DATUM_GEO, CVT_V965_GET_DATUM_OV, CVT_V965_GET_DATUM_UN, CVT_V965_TYPE_A, CVT_V965A_GET_DATUM_CH, FALSE, cvt_V792_data::m_queue, cvt_V792_data::m_queue_end, cvt_V792_data::m_queue_ini, cvt_V792_data::m_type, TRACE1, and TRUE.
CVT_DLL_API BOOL cvt_V792_peek_event (cvt_V792_data * p_data, UINT32 * out_buff, long * p_out_buff_size, UINT32 * p_event_count, BOOL dequeue)
Tries to peek (i.e. copy but not removing) an event from queue and save data to output buffer.
Scans the queue beginning from m_queue_ini, searching for an event block, and stores data output stream.
Parameters:
p_data Pointer to board data
out_buff Pointer to output buffer
p_out_buff_size Size of out_buff (UINT32). The number of data written into out_buff (UINT32) on exit.
p_event_count The found event count
dequeue If TRUE removes the found events from queue
Returns:
TRUE: some event found FALSE elsewhere
Definition at line 1609 of file cvt_V792.c.
References CVT_QTP_GET_EOB_EVENT_COUNT, CVT_QTP_IS_EOB, CVT_QTP_IS_HEADER, cvt_V792_dequeue(), CVT_V792_QUEUE_SIZE_DWORD, FALSE, cvt_V792_data::m_queue, cvt_V792_data::m_queue_end, cvt_V792_data::m_queue_ini, and TRUE.
CVT_DLL_API BOOL cvt_V792_read_data (cvt_V792_data * p_data)
Reads new data from MEB and stores into internal queue.
Reads the largest allowed buffer (queue free size) from MEB and stores into queue
Parameters:
p_data Pointer to board data
Returns:
TRUE: Procedure successfully executed
Definition at line 1565 of file cvt_V792.c.
References cvt_V792_get_queue_free(), cvt_V792_inqueue(), cvt_V792_read_MEB(), FALSE, TRACE, and TRUE.
CVT_DLL_API BOOL cvt_V792_read_MEB (cvt_V792_data * p_data, void * p_buff, UINT32 * p_buff_size)
Reads data from Multiple event buffer and stores to user buffer.
Call cvt_FIFO_BLT_read for Multiple Event Buffer and stores data into user buffer. If the returned data is just a V792 not valid datum, this is discarded.
Parameters:
p_data Pointer to board data
p_buff The target buffer: caller allocated
p_buff_size The buffer size (bytes). On exit will holds the number of bytes really read.
Returns:
TRUE: Procedure successfully executed
See also:
cvt_FIFO_BLT_read
Definition at line 1181 of file cvt_V792.c.
References cvt_FIFO_BLT_read(), CVT_QTP_IS_NOT_VALID_DATUM, CVT_V792_OUT_BUFFER_ADD, CVT_V792_OUT_BUFFER_AM, CVT_V792_OUT_BUFFER_DATA_SIZE, FALSE, cvt_V792_data::m_common_data, and TRUE.
Referenced by cvt_V792_read_data().
CVT_DLL_API BOOL cvt_V792_set_acquisition_mode (cvt_V792_data * p_data, BOOL sliding_scale_enable, BOOL zero_suppression_enable, BOOL overflow_suppression_enable, BOOL empty_enable, BOOL count_all_events)
Setups the acquisition mode parameters.
Setups the relevant parameters for the acquisition mode.
Parameters:
p_data Pointer to board data
sliding_scale_enable Enable/Disable the sliding scale feature.
zero_suppression_enable Enable/Disable the zero suppression feature.
overflow_suppression_enable Enable/Disable the overflow suppression feature.
empty_enable Enable/Disable empty event storing feature.
count_all_events Enable counting all triggers or accepted one only.
Returns:
TRUE: Procedure successfully executed
Definition at line 1215 of file cvt_V792.c.
References CVT_V792_BIT_CLEAR_2_INDEX, CVT_V792_BIT_SET_2_INDEX, CVT_V792_BSC2_ALL_TRG_MSK, CVT_V792_BSC2_EMPTY_EN_MSK, CVT_V792_BSC2_LOW_THR_DIS_MSK, CVT_V792_BSC2_OVER_RANGE_DIS_MSK, CVT_V792_BSC2_SLIDE_EN_MSK, cvt_write_reg(), FALSE, cvt_V792_data::m_common_data, TRACE, and TRUE.
CVT_DLL_API BOOL cvt_V792_set_ader_high (cvt_V792_data * p_data, UINT8 value)
Set the address decoder high register.
Writes the specified value to the address decoder high register.
Parameters:
p_data Pointer to board data
value The value to set
Returns:
TRUE: Procedure successfully executed
Definition at line 457 of file cvt_V792.c.
References CVT_V792_ADER_HIGH_INDEX, cvt_write_reg(), FALSE, cvt_V792_data::m_common_data, TRACE, and TRUE.
CVT_DLL_API BOOL cvt_V792_set_bit_clear_1 (cvt_V792_data * p_data, UINT16 value)
Set the bit clear 1 register.
Writes the specified value to the bit clear 1 register.
Parameters:
p_data Pointer to board data
value The value to set
Returns:
TRUE: Procedure successfully executed
Definition at line 303 of file cvt_V792.c.
References CVT_V792_BIT_CLEAR_1_INDEX, cvt_write_reg(), FALSE, cvt_V792_data::m_common_data, TRACE, and TRUE.
CVT_DLL_API BOOL cvt_V792_set_bit_clear_2 (cvt_V792_data * p_data, UINT16 value)
Set the bit clear 2 register.
Writes the specified value to the bit clear 2 register.
Parameters:
p_data Pointer to board data
value The value to set
Returns:
TRUE: Procedure successfully executed
Definition at line 831 of file cvt_V792.c.
References CVT_V792_BIT_CLEAR_2_INDEX, cvt_write_reg(), FALSE, cvt_V792_data::m_common_data, TRACE, and TRUE.
CVT_DLL_API BOOL cvt_V792_set_bit_set_1 (cvt_V792_data * p_data, UINT16 value)
Set the bit set 1 register.
Writes the specified value to the bit set 1 register.
Parameters:
p_data Pointer to board data
value The value to set
Returns:
TRUE: Procedure successfully executed
Definition at line 288 of file cvt_V792.c.
References CVT_V792_BIT_SET_1_INDEX, cvt_write_reg(), FALSE, cvt_V792_data::m_common_data, TRACE, and TRUE.
CVT_DLL_API BOOL cvt_V792_set_bit_set_2 (cvt_V792_data * p_data, UINT16 value)
Set the bit set 2 register.
Writes the specified value to the bit set 2 register.
Parameters:
p_data Pointer to board data
value The value to set
Returns:
TRUE: Procedure successfully executed
Definition at line 816 of file cvt_V792.c.
References CVT_V792_BIT_SET_2_INDEX, cvt_write_reg(), FALSE, cvt_V792_data::m_common_data, TRACE, and TRUE.
CVT_DLL_API BOOL cvt_V792_set_bitmask_control_1 (cvt_V792_data * p_data, CVT_V792_CONTROL_1_MSK value)
Set a bitmask to control 1 register.
Sets the bits of the bitmask into the register. The bitmask is ORed to the actual regiter content
Parameters:
p_data Pointer to board data
value The bitmask to set : may be a combination of CVT_V792_CONTROL_1_MSK bitmask
Returns:
TRUE: Procedure successfully executed
See also:
CVT_V792_CONTROL_1_MSK
Definition at line 427 of file cvt_V792.c.
References cvt_set_bitmask(), CVT_V792_CONTROL_1_ADD, CVT_V792_CONTROL_1_AM, CVT_V792_CONTROL_1_DATA_SIZE, FALSE, cvt_V792_data::m_common_data, TRACE, and TRUE.
CVT_DLL_API BOOL cvt_V792_set_control_1 (cvt_V792_data * p_data, UINT16 value)
Set to control 1 register.
Writes the specified value to the control 1 register.
Parameters:
p_data Pointer to board data
value The value to write
Returns:
TRUE: Procedure successfully executed
See also:
CVT_V792_CONTROL_1_MSK
Definition at line 396 of file cvt_V792.c.
References CVT_V792_CONTROL_1_INDEX, cvt_write_reg(), FALSE, cvt_V792_data::m_common_data, TRACE, and TRUE.
CVT_DLL_API BOOL cvt_V792_set_crate_number (cvt_V792_data * p_data, UINT8 crate_number)
Setups the crate number.
Parameters:
p_data Pointer to board data
crate_number The crate number.
Returns:
TRUE: Procedure successfully executed
Definition at line 1383 of file cvt_V792.c.
References CVT_V792_CRATE_SELECT_INDEX, cvt_write_reg(), FALSE, cvt_V792_data::m_common_data, TRACE, and TRUE.
CVT_DLL_API BOOL cvt_V792_set_dual_range_threshold (cvt_V792_data * p_data, cvt_V792_threshold_id threshold_id, UINT16 value_high, UINT16 value_low)
Set the specified threshold register for dual range board (V965 and V1785).
Writes the specified value to the specified threshold register as high and low part. If threshold_id is CVT_V792_THRESHOLD_ALL every threshold will be setted to the same value.
Parameters:
p_data Pointer to board data
threshold_id The threshold to set. It must be a cvt_V792_threshold_id valid id.
value_high The high value to set : Threshold value and Kill bit (CVT_V792_THRESHOLD_KILL_MSK) If the kill bit be isn't setted the channel will be disabled
value_low The low value to set : Threshold value and Kill bit (CVT_V792_THRESHOLD_KILL_MSK) If the kill bit be isn't setted the channel will be disabled
Returns:
TRUE: Procedure successfully executed
See also:
cvt_V792_threshold_id
CVT_V792_THRESHOLD_KILL_MSK
< The board is V965
< The board is V965A
< The board is V1785
Definition at line 716 of file cvt_V792.c.
References CVT_QTP_NUM_CHANNELS, CVT_V1785, CVT_V792_THRESHOLD_0, CVT_V792_THRESHOLD_0_INDEX, CVT_V792_THRESHOLD_1, CVT_V792_THRESHOLD_10, CVT_V792_THRESHOLD_11, CVT_V792_THRESHOLD_12, CVT_V792_THRESHOLD_13, CVT_V792_THRESHOLD_14, CVT_V792_THRESHOLD_15, CVT_V792_THRESHOLD_16, CVT_V792_THRESHOLD_17, CVT_V792_THRESHOLD_18, CVT_V792_THRESHOLD_19, CVT_V792_THRESHOLD_2, CVT_V792_THRESHOLD_20, CVT_V792_THRESHOLD_21, CVT_V792_THRESHOLD_22, CVT_V792_THRESHOLD_23, CVT_V792_THRESHOLD_24, CVT_V792_THRESHOLD_25, CVT_V792_THRESHOLD_26, CVT_V792_THRESHOLD_27, CVT_V792_THRESHOLD_28, CVT_V792_THRESHOLD_29, CVT_V792_THRESHOLD_3, CVT_V792_THRESHOLD_30, CVT_V792_THRESHOLD_31, CVT_V792_THRESHOLD_4, CVT_V792_THRESHOLD_5, CVT_V792_THRESHOLD_6, CVT_V792_THRESHOLD_7, CVT_V792_THRESHOLD_8, CVT_V792_THRESHOLD_9, CVT_V792_THRESHOLD_ALL, CVT_V965, CVT_V965_TYPE_A, cvt_write_reg(), FALSE, cvt_V792_data::m_common_data, cvt_V792_data::m_type, TRACE1, and TRUE.
CVT_DLL_API BOOL cvt_V792_set_dual_range_zero_suppression (cvt_V792_data * p_data, BOOL enable, BOOL step_threshold, const UINT16 * thresholds_buff_high, const UINT16 * thresholds_buff_low)
Setups the zero suppression feature for dual range boards (V965 or V1785).
Enable/ Disable zero suppression and setups other relevant parameters.
Parameters:
p_data Pointer to board data
enable Enable/disable the zero suppression (low threshold check).
step_threshold If setted the comparison is ADC CONVERTED VALUE < THRESHOLD VALUE x 2, otherwise ADC CONVERTED VALUE < THRESHOLD VALUE x 16
thresholds_buff_high The high thresholds buffer: It must contain as many values as specified for the board type (CVT_QTP_NUM_CHANNELS). It may be NULL (e.g. when disabling this feature or the thresholds are already setted) The value consists of the threshold level and the kill bit (CVT_V792_THRESHOLD_KILL_MSK) If the kill bit be isn't setted the channel will be disabled
thresholds_buff_low The low thresholds buffer: It must contain as many values as specified for the board type (CVT_QTP_NUM_CHANNELS). It may be NULL (e.g. when disabling this feature or the thresholds are already setted) The value consists of the threshold level and the kill bit (CVT_V792_THRESHOLD_KILL_MSK) If the kill bit be isn't setted the channel will be disabled
Returns:
TRUE: Procedure successfully executed
See also:
CVT_V792_THRESHOLD_KILL_MSK
< The board is V965
< The board is V965A
< The board is V1785
Definition at line 963 of file cvt_V792.c.
References CVT_QTP_NUM_CHANNELS, CVT_V1785, CVT_V792_BIT_CLEAR_2_INDEX, CVT_V792_BIT_SET_2_INDEX, CVT_V792_BSC2_LOW_THR_DIS_MSK, CVT_V792_BSC2_STEP_TH_MSK, CVT_V792_THRESHOLD_0, CVT_V792_THRESHOLD_0_INDEX, CVT_V965, CVT_V965_TYPE_A, cvt_write_reg(), FALSE, cvt_V792_data::m_common_data, cvt_V792_data::m_type, TRACE, TRACE1, and TRUE.
CVT_DLL_API BOOL cvt_V792_set_event_counter (cvt_V792_data * p_data, BOOL count_all_events, BOOL reset_count)
Setups the event counter.
Setups the relevant parameters for the event counter.
Parameters:
p_data Pointer to board data
count_all_events Enable counting all events or accepted ones only.
reset_count If TRUE resets the event counter.
Returns:
TRUE: Procedure successfully executed
Definition at line 1139 of file cvt_V792.c.
References CVT_V792_BIT_CLEAR_2_INDEX, CVT_V792_BIT_SET_2_INDEX, CVT_V792_BSC2_ALL_TRG_MSK, CVT_V792_EVENT_COUNT_RESET_INDEX, cvt_write_reg(), FALSE, cvt_V792_data::m_common_data, TRACE, and TRUE.
CVT_DLL_API BOOL cvt_V792_set_event_trigger (cvt_V792_data * p_data, UINT8 value)
Set the Event trigger register.
Writes the specified value to the Event trigger register.
Parameters:
p_data Pointer to board data
value The value to set
Returns:
TRUE: Procedure successfully executed
Definition at line 565 of file cvt_V792.c.
References CVT_V792_EVENT_TRG_INDEX, cvt_write_reg(), FALSE, cvt_V792_data::m_common_data, TRACE, and TRUE.
CVT_DLL_API BOOL cvt_V792_set_fast_clear_window (cvt_V792_data * p_data, UINT16 value)
Set the fast clear window register.
Writes the specified value to the fast clear window register.
Parameters:
p_data Pointer to board data
value The value to set
Returns:
TRUE: Procedure successfully executed
Definition at line 1200 of file cvt_V792.c.
References CVT_V792_FCLR_WND_INDEX, cvt_write_reg(), FALSE, cvt_V792_data::m_common_data, TRACE, and TRUE.
CVT_DLL_API BOOL cvt_V792_set_geo_address (cvt_V792_data * p_data, UINT8 value)
Sets the geographical address.
Writes the geographical address register.
Parameters:
p_data Pointer to board data
value The value to write
Returns:
TRUE: Procedure successfully executed
Definition at line 226 of file cvt_V792.c.
References CVT_V792_GEO_ADDRESS_INDEX, cvt_write_reg(), FALSE, cvt_V792_data::m_common_data, TRACE, and TRUE.
CVT_DLL_API BOOL cvt_V792_set_interrupt (cvt_V792_data * p_data, UINT8 level, UINT8 vector, UINT8 event_number)
Setups interrupt parameters.
Setups the relevant parameters for interrupt usage.
Parameters:
p_data Pointer to board data
level The interrupt level.
vector The interrupt vector.
event_number The number of events to get an interrupt (setting 0 interrupt feature is disabled).
Returns:
TRUE: Procedure successfully executed
Definition at line 1267 of file cvt_V792.c.
References CVT_V792_EVENT_TRG_INDEX, CVT_V792_INT_LEVEL_INDEX, CVT_V792_INT_VECTOR_INDEX, cvt_write_reg(), FALSE, cvt_V792_data::m_common_data, TRACE, and TRUE.
CVT_DLL_API BOOL cvt_V792_set_interrupt_level (cvt_V792_data * p_data, UINT8 value)
Set the interrupt level register.
Writes the specified value to the interrupt level register.
Parameters:
p_data Pointer to board data
value The value to set
Returns:
TRUE: Procedure successfully executed
Definition at line 318 of file cvt_V792.c.
References CVT_V792_INT_LEVEL_INDEX, cvt_write_reg(), FALSE, cvt_V792_data::m_common_data, TRACE, and TRUE.
CVT_DLL_API BOOL cvt_V792_set_interrupt_vector (cvt_V792_data * p_data, UINT8 value)
Set the interrupt level register.
Writes the specified value to the interrupt vector register.
Parameters:
p_data Pointer to board data
value The value to set
Returns:
TRUE: Procedure successfully executed
Definition at line 349 of file cvt_V792.c.
References CVT_V792_INT_VECTOR_INDEX, cvt_write_reg(), FALSE, cvt_V792_data::m_common_data, TRACE, and TRUE.
CVT_DLL_API BOOL cvt_V792_set_MCST_CBLT (cvt_V792_data * p_data, UINT8 address, MCST_CBLT_board_pos pos)
Setups MCST/CBLT parameters this board.
Setups the relevant parameters for MCST/CBLT usage.
Parameters:
p_data Pointer to board data.
address The MCST/CBLT address.
pos The board position into the MCST / CBLT chain: it must be a MCST_CBLT_board_pos identifier
Returns:
TRUE: Procedure successfully executed
See also:
MCST_CBLT_board_pos
Definition at line 1947 of file cvt_V792.c.
References CVT_V792_MCCTRL_DISABLED_BOARD_MSK, CVT_V792_MCCTRL_FIRST_BOARD_MSK, CVT_V792_MCCTRL_LAST_BOARD_MSK, CVT_V792_MCCTRL_MID_BOARD_MSK, CVT_V792_MCST_CBLT_ADDRESS_INDEX, CVT_V792_MCST_CBLT_CTRL_INDEX, cvt_write_reg(), FALSE, cvt_V792_data::m_common_data, MCST_CBLT_board_disabled, MCST_CBLT_board_pos_first, MCST_CBLT_board_pos_last, MCST_CBLT_board_pos_mid, TRACE, TRACE1, and TRUE.
Referenced by cvt_V792_open().
CVT_DLL_API BOOL cvt_V792_set_MCST_CBLT_address (cvt_V792_data * p_data, UINT8 value)
Sets the MCST\CBLT address.
Writes the geographical address register. This register contains the most significant bits of the MCST/CBLT address of the module set via VME.
Parameters:
p_data Pointer to board data
value The value to write
Returns:
TRUE: Procedure successfully executed
Definition at line 257 of file cvt_V792.c.
References CVT_V792_MCST_CBLT_ADDRESS_INDEX, cvt_write_reg(), FALSE, cvt_V792_data::m_common_data, TRACE, and TRUE.
CVT_DLL_API BOOL cvt_V792_set_MCST_CBLT_control (cvt_V792_data * p_data, UINT8 value)
Set the MCST/CBLT Control register.
Writes the specified value to the MCST/CBLT Control register.
Parameters:
p_data Pointer to board data
value The value to set
Returns:
TRUE: Procedure successfully executed
Definition at line 534 of file cvt_V792.c.
References CVT_V792_MCST_CBLT_CTRL_INDEX, cvt_write_reg(), FALSE, cvt_V792_data::m_common_data, TRACE, and TRUE.
CVT_DLL_API BOOL cvt_V792_set_MEB (cvt_V792_data * p_data, BOOL empty_enable, BOOL auto_incr_enable)
Setups the Multiple Event Buffer.
Setups the relevant parameters for the Multiple Event Buffer.
Parameters:
p_data Pointer to board data
empty_enable Enable/disable storing events with no data (only header and EOB).
auto_incr_enable Enable/disable the event counter autoincrement feature.
Returns:
TRUE: Procedure successfully executed
Definition at line 1089 of file cvt_V792.c.
References CVT_V792_BIT_CLEAR_2_INDEX, CVT_V792_BIT_SET_2_INDEX, CVT_V792_BSC2_AUTO_INC_MSK, CVT_V792_BSC2_EMPTY_EN_MSK, cvt_write_reg(), FALSE, cvt_V792_data::m_common_data, TRACE, and TRUE.
CVT_DLL_API BOOL cvt_V792_set_overflow_suppression (cvt_V792_data * p_data, BOOL enable)
Setups the overflow suppression feature.
Enable/ Disable overflow suppression and setups other relevant parameters.
Parameters:
p_data Pointer to board data
enable Enable/disable the overflow suppression.
Returns:
TRUE: Procedure successfully executed
Definition at line 1059 of file cvt_V792.c.
References CVT_V792_BIT_CLEAR_2_INDEX, CVT_V792_BIT_SET_2_INDEX, CVT_V792_BSC2_OVER_RANGE_DIS_MSK, cvt_write_reg(), FALSE, cvt_V792_data::m_common_data, TRACE, and TRUE.
CVT_DLL_API BOOL cvt_V792_set_pedestal (cvt_V792_data * p_data, UINT8 value)
Set the pedestal value.
Writes the specified value to the Iped register
Parameters:
p_data Pointer to board data
value The value to set
Returns:
TRUE: Procedure successfully executed
Definition at line 1401 of file cvt_V792.c.
References CVT_V792_IPED_INDEX, cvt_write_reg(), FALSE, cvt_V792_data::m_common_data, TRACE, and TRUE.
CVT_DLL_API BOOL cvt_V792_set_readout_mode (cvt_V792_data * p_data, BOOL bus_error_enable, BOOL block_end_enable, BOOL align64_enable)
Setups data readout mode parameters.
Setups the relevant parameters for data readout.
Parameters:
p_data Pointer to board data
bus_error_enable Enable bus error: the module is enabled to generate a Bus error to finish a block transfer.
block_end_enable Enable block end: the module sends all data to the CPU until the first EOB word (end of first event) is reached;
align64_enable Enable align 64: the module is enabled to add dummy word when the number of words is odd.
Returns:
TRUE: Procedure successfully executed
Definition at line 1310 of file cvt_V792.c.
References cvt_clear_bitmask_reg(), cvt_set_bitmask_reg(), CVT_V792_CONTROL_1_INDEX, CVT_V792_CTRL1_ALIGN64_MSK, CVT_V792_CTRL1_BERR_ENABLE_MSK, CVT_V792_CTRL1_BLKEND_MSK, FALSE, cvt_V792_data::m_common_data, TRACE, and TRUE.
CVT_DLL_API BOOL cvt_V792_set_sliding_scale (cvt_V792_data * p_data, BOOL enable)
Setups the sliding scale feature.
Enable/ Disable sliding scale.
Parameters:
p_data Pointer to board data
enable Enable/disable the sliding scale
Returns:
TRUE: Procedure successfully executed
Definition at line 852 of file cvt_V792.c.
References CVT_V792_BIT_CLEAR_2_INDEX, CVT_V792_BIT_SET_2_INDEX, CVT_V792_BSC2_SLIDE_EN_MSK, cvt_write_reg(), FALSE, cvt_V792_data::m_common_data, TRACE, and TRUE.
CVT_DLL_API BOOL cvt_V792_set_threshold (cvt_V792_data * p_data, cvt_V792_threshold_id threshold_id, UINT16 value)
Set the specified threshold register.
Writes the specified value to the specified threshold register. If threshold_id is CVT_V792_THRESHOLD_ALL every threshold will be setted to the same value.
Parameters:
p_data Pointer to board data
threshold_id The threshold to set. It must be a cvt_V792_threshold_id valid id.
value The value to set : Threshold value and Kill bit (CVT_V792_THRESHOLD_KILL_MSK) If the kill bit be isn't setted the channel will be disabled
Returns:
TRUE: Procedure successfully executed
See also:
cvt_V792_threshold_id
CVT_V792_THRESHOLD_KILL_MSK
< The board is V792A
< The board is V792N
< The board is V862A
< The board is V785A
< The board is V785N
< The board is V775A
< The board is V775N
Definition at line 613 of file cvt_V792.c.
References CVT_QTP_NUM_CHANNELS, CVT_V775_TYPE_A, CVT_V775_TYPE_N, CVT_V785_TYPE_A, CVT_V785_TYPE_N, CVT_V792_THRESHOLD_0, CVT_V792_THRESHOLD_0_INDEX, CVT_V792_THRESHOLD_1, CVT_V792_THRESHOLD_10, CVT_V792_THRESHOLD_11, CVT_V792_THRESHOLD_12, CVT_V792_THRESHOLD_13, CVT_V792_THRESHOLD_14, CVT_V792_THRESHOLD_15, CVT_V792_THRESHOLD_16, CVT_V792_THRESHOLD_17, CVT_V792_THRESHOLD_18, CVT_V792_THRESHOLD_19, CVT_V792_THRESHOLD_2, CVT_V792_THRESHOLD_20, CVT_V792_THRESHOLD_21, CVT_V792_THRESHOLD_22, CVT_V792_THRESHOLD_23, CVT_V792_THRESHOLD_24, CVT_V792_THRESHOLD_25, CVT_V792_THRESHOLD_26, CVT_V792_THRESHOLD_27, CVT_V792_THRESHOLD_28, CVT_V792_THRESHOLD_29, CVT_V792_THRESHOLD_3, CVT_V792_THRESHOLD_30, CVT_V792_THRESHOLD_31, CVT_V792_THRESHOLD_4, CVT_V792_THRESHOLD_5, CVT_V792_THRESHOLD_6, CVT_V792_THRESHOLD_7, CVT_V792_THRESHOLD_8, CVT_V792_THRESHOLD_9, CVT_V792_THRESHOLD_ALL, CVT_V792_TYPE_A, CVT_V792_TYPE_N, CVT_V862_TYPE_A, cvt_write_reg(), FALSE, cvt_V792_data::m_common_data, cvt_V792_data::m_type, TRACE1, and TRUE.
CVT_DLL_API BOOL cvt_V792_set_zero_suppression (cvt_V792_data * p_data, BOOL enable, BOOL step_threshold, const UINT16 * thresholds_buff)
Setups the zero suppression feature.
Enable/ Disable zero suppression and setups other relevant parameters.
Parameters:
p_data Pointer to board data
enable Enable/disable the zero suppression (low threshold check).
step_threshold If setted the comparison is ADC CONVERTED VALUE < THRESHOLD VALUE x 2, otherwise ADC CONVERTED VALUE < THRESHOLD VALUE x 16
thresholds_buff The thresholds buffer: It must contain as many values as specified for the board type (CVT_QTP_NUM_CHANNELS). It may be NULL (e.g. when disabling this feature or the thresholds are already setted) The value consists of the threshold level and the kill bit (CVT_V792_THRESHOLD_KILL_MSK) If the kill bit be isn't setted the channel will be disabled
Returns:
TRUE: Procedure successfully executed
See also:
CVT_V792_THRESHOLD_KILL_MSK
< The board is V792A
< The board is V792N
< The board is V862A
< The board is V785A
< The board is V785N
< The board is V775A
< The board is V775N
Definition at line 868 of file cvt_V792.c.
References CVT_QTP_NUM_CHANNELS, CVT_V775_TYPE_A, CVT_V775_TYPE_N, CVT_V785_TYPE_A, CVT_V785_TYPE_N, CVT_V792_BIT_CLEAR_2_INDEX, CVT_V792_BIT_SET_2_INDEX, CVT_V792_BSC2_LOW_THR_DIS_MSK, CVT_V792_BSC2_STEP_TH_MSK, CVT_V792_THRESHOLD_0, CVT_V792_THRESHOLD_0_INDEX, CVT_V792_TYPE_A, CVT_V792_TYPE_N, CVT_V862_TYPE_A, cvt_write_reg(), FALSE, cvt_V792_data::m_common_data, cvt_V792_data::m_type, TRACE, TRACE1, and TRUE.
CVT_DLL_API BOOL cvt_V792_single_shot_reset (cvt_V792_data * p_data)
Perfoms a single shot reset.
Writes a dummy value to the single shot reset register.
Parameters:
p_data Pointer to board data
Returns:
TRUE: Procedure successfully executed
Warning:
This register must be used very carefully and for debugging purposes only. In order to reset the board, it is recommended to use the Bit Set 1 Register
See also:
cvt_V792_set_bitmask_control_1
Definition at line 519 of file cvt_V792.c.
References CVT_V792_SINGLE_SHOT_RESET_INDEX, cvt_write_reg(), FALSE, cvt_V792_data::m_common_data, TRACE, and TRUE.
CVT_DLL_API BOOL cvt_V792_software_reset (cvt_V792_data * p_data)
Performs a software reset.
Writes a dummy value into CVT_V792_SINGLE_SHOT_RESET register.
Parameters:
p_data Pointer to board data
Returns:
TRUE: Procedure successfully executed
Definition at line 1501 of file cvt_V792.c.
References CVT_V792_SINGLE_SHOT_RESET_INDEX, cvt_write_reg(), FALSE, cvt_V792_data::m_common_data, TRACE, and TRUE.
CVT_DLL_API const char* cvt_V792_SW_rev (void)
Returns the SDK software release.
Returns:
const char*: The SDK revision string
Definition at line 1994 of file cvt_V792.c.